"""Build the original 5x7 dot lettering used by the scoreboard (no web font request)."""
from pathlib import Path
from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen
from io import BytesIO
import base64
patterns = {
'A':'01110 10001 10001 11111 10001 10001 10001','B':'11110 10001 10001 11110 10001 10001 11110',
'C':'01111 10000 10000 10000 10000 10000 01111','D':'11110 10001 10001 10001 10001 10001 11110',
'E':'11111 10000 10000 11110 10000 10000 11111','F':'11111 10000 10000 11110 10000 10000 10000',
'G':'01111 10000 10000 10111 10001 10001 01111','H':'10001 10001 10001 11111 10001 10001 10001',
'I':'11111 00100 00100 00100 00100 00100 11111','J':'00111 00010 00010 00010 10010 10010 01100',
'K':'10001 10010 10100 11000 10100 10010 10001','L':'10000 10000 10000 10000 10000 10000 11111',
'M':'10001 11011 10101 10101 10001 10001 10001','N':'10001 11001 10101 10011 10001 10001 10001',
'O':'01110 10001 10001 10001 10001 10001 01110','P':'11110 10001 10001 11110 10000 10000 10000',
'Q':'01110 10001 10001 10001 10101 10010 01101','R':'11110 10001 10001 11110 10100 10010 10001',
'S':'01111 10000 10000 01110 00001 00001 11110','T':'11111 00100 00100 00100 00100 00100 00100',
'U':'10001 10001 10001 10001 10001 10001 01110','V':'10001 10001 10001 10001 10001 01010 00100',
'W':'10001 10001 10001 10101 10101 11011 10001','X':'10001 10001 01010 00100 01010 10001 10001',
'Y':'10001 10001 01010 00100 00100 00100 00100','Z':'11111 00001 00010 00100 01000 10000 11111',
'0':'01110 10001 10011 10101 11001 10001 01110','1':'00100 01100 00100 00100 00100 00100 01110',
'2':'01110 10001 00001 00010 00100 01000 11111','3':'11110 00001 00001 01110 00001 00001 11110',
'4':'00010 00110 01010 10010 11111 00010 00010','5':'11111 10000 10000 11110 00001 00001 11110',
'6':'01110 10000 10000 11110 10001 10001 01110','7':'11111 00001 00010 00100 01000 01000 01000',
'8':'01110 10001 10001 01110 10001 10001 01110','9':'01110 10001 10001 01111 00001 00001 01110',
' ':'00000 00000 00000 00000 00000 00000 00000','—':'00000 00000 00000 11111 00000 00000 00000'}
for char,base,accent in [('Å','A',['00100','01010','00100']),('Ä','A',['01010','00000']),('Ö','O',['01010','00000']),('É','E',['00010','00100'])]:
    patterns[char]=' '.join(accent)+' '+patterns[base]
fb=FontBuilder(1000,isTTF=True);glyphs={};names={c:'u'+hex(ord(c))[2:] for c in patterns}
for char,pattern in patterns.items():
    pen=TTGlyphPen(None);rows=pattern.split()
    for y,row in enumerate(rows):
        for x,on in enumerate(row):
            if on=='1':
                left=60+x*100;bottom=(len(rows)-1-y)*100
                pen.moveTo((left,bottom));pen.lineTo((left+72,bottom));pen.lineTo((left+72,bottom+72));pen.lineTo((left,bottom+72));pen.closePath()
    glyphs[names[char]]=pen.glyph()
glyphs['.notdef']=TTGlyphPen(None).glyph();fb.setupGlyphOrder(['.notdef',*names.values()]);fb.setupCharacterMap({ord(c):n for c,n in names.items()});fb.setupGlyf(glyphs)
fb.setupHorizontalMetrics({n:(620,60) for n in glyphs});fb.setupHorizontalHeader(ascent=1000,descent=-150)
fb.setupNameTable({'familyName':'Skolarkaden LED','styleName':'Regular','uniqueFontIdentifier':'SkolarkadenLED1','fullName':'Skolarkaden LED','psName':'SkolarkadenLED'})
fb.setupOS2(sTypoAscender=1000,sTypoDescender=-150,usWinAscent=1000,usWinDescent=150);fb.setupPost();fb.font.flavor='woff';out=BytesIO();fb.font.save(out)
Path(__file__).resolve().parents[1].joinpath('resources/led-font.css').write_text("/* Original Skolarkaden dot font; generated by dev/build-led-font.py. */\n@font-face{font-family:SkolarkadenLED;src:url(data:font/woff;base64,"+base64.b64encode(out.getvalue()).decode()+") format('woff');font-weight:400;font-style:normal;font-display:swap}\n")
