// Authored, development-only controls; omitted from the downloadable app.
addEventListener('DOMContentLoaded',()=>{
 const SC=Starlight;let g,renderer;const start=SC.PaintGame.prototype.start,draw=SC.PaintRenderer.prototype.draw;
 SC.PaintGame.prototype.start=function(...args){const v=start.apply(this,args);g=this;return v;};SC.PaintRenderer.prototype.draw=function(...args){renderer=this;return draw.apply(this,args);};
 const panel=document.createElement('div');panel.style.cssText='padding:8px;display:flex;gap:7px;flex-wrap:wrap';document.body.prepend(panel);const status=document.createElement('span');status.id='paint-audit-status';panel.append(status);
 function fill(){if(!g)return;g.queue.clear();g.people=[];g.puddles=[];g.job=null;g.balloon=null;g.child.jump=null;g.child.x=.49;g.child.y=.4;g.child.roof=1;g.passed=0;g.spawned=0;g.score=g.hits=0;g.maxPeople=8;g.spawnIn=10000;
  for(let i=0;i<8;i++){g.spawn();const p=g.people.at(-1);p.x=[.14,.36,.57,.78,.22,.46,.70,.90][i];p.lane=i%3;p.y=[.80,.865,.93][p.lane];}g.state='paused';}
 const actions=[['Fyll gatan med åtta etiketter',fill],['Visa färgstänk',()=>{fill();for(const [i,color] of [[0,'#b398ef'],[3,'#ff779e']]){const p=g.people[i];p.paint=g.paintMarks(color);p.status='angry';p.reactionAge=.27;}for(const [x,color] of [[.18,'#69d3ee'],[.43,'#ffd66b'],[.68,'#ffae70']])g.puddles.push({x,y:.97,...g.paintMarks(color)});for(const p of g.getTargets().slice(0,3))g.queue.enqueue(p.item.answer);}],['Visa takhopp',()=>{fill();const p=g.people[0];p.x=.1;p.direction=-1;g.queue.enqueue(p.item.answer);g.state='playing';for(let i=0;i<60&&!g.child.jump;i++)g.update(.05);for(let i=0;i<5;i++)g.update(.05);g.state='paused';}],['Spela fixturen',()=>{if(g){g.state='playing';g.spawnIn=1;}}],['Slutför fyrtio',()=>{if(!g)return;g.queue.clear();g.job=null;g.balloon=null;g.people=[];g.spawned=g.passed=40;g.state='playing';g.update(.05);}],['Granska etiketter',()=>{if(!renderer)return;const boxes=renderer.labelBoxes||[];let n=0;boxes.forEach((a,i)=>boxes.slice(i+1).forEach(b=>{if(a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y)n++;}));status.textContent=boxes.length+' etiketter · '+n+' överlappningar · '+g.width+' px';}]];
 for(const [name,run] of actions){const b=document.createElement('button');b.textContent=name;b.onclick=run;panel.append(b);}
});
