/* DOM/Canvas stand-ins exercise the actual HTML script order and app wiring.
   This is a Node integration check, not a browser or microphone hardware test. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const base=path.join(__dirname,'..'),html=fs.readFileSync(path.join(base,'index.html'),'utf8');
class CustomEvent extends Event{constructor(type,{detail}={}){super(type);this.detail=detail;}}
const context2d=new Proxy({},{get:(_,key)=>key==='measureText'?s=>({width:[...s].length*9}):key==='createLinearGradient'||key==='createRadialGradient'?()=>({addColorStop(){}}):()=>{}});
class Element extends EventTarget{
 constructor(){super();Object.assign(this,{value:'',textContent:'',text:'',hidden:false,disabled:false,checked:false,children:[],options:[],dataset:{},className:'',open:false});this.classList={add(){},remove(){},toggle(){}};}
 append(...items){this.children.push(...items);}replaceChildren(...items){this.children=[...items];}add(option){this.options.push(option);if(this.options.length===1)this.value=option.value;}
 closest(){return this.parent||(this.parent=new Element());}querySelector(selector){return this.noSubmit&&selector==='[type=submit]'?null:this.button||(this.button=new Element());}setAttribute(){}focus(){}select(){}remove(){}showModal(){this.open=true;}close(){this.open=false;this.dispatchEvent(new Event('close'));}
 getBoundingClientRect(){return {width:1000,height:700};}getContext(){return context2d;}
}
const elements={};for(const tag of html.match(/<[^>]+\bid="[^"]+"[^>]*>/g)||[]){const id=tag.match(/\bid="([^"]+)"/)[1],el=new Element();el.hidden=/\bhidden\b/.test(tag);el.checked=/\bchecked\b/.test(tag);elements[id]=el;}
for(const [,id,body] of html.matchAll(/<select[^>]*\bid="([^"]+)"[^>]*>([\s\S]*?)<\/select>/g))for(const [,value,text] of body.matchAll(/<option value="([^"]*)"[^>]*>([^<]*)<\/option>/g)){const option=new Element();option.value=value;option.text=text;elements[id].add(option);}
elements['answer-form'].noSubmit=true;
const radios=[...html.matchAll(/<input[^>]*name="game"[^>]*value="([^"]+)"[^>]*>/g)].map(([,value])=>Object.assign(new Element(),{value}));
const document=Object.assign(new EventTarget(),{hidden:false,body:new Element(),getElementById:id=>{assert(elements[id],'unknown DOM id '+id);return elements[id];},createElement:()=>new Element(),createDocumentFragment:()=>new Element(),querySelector:()=>null,querySelectorAll:selector=>selector==='[name=game]'?radios:[]});
const raf=new Map(),storage=new Map();let rafId=0,now=0,currentGame;const recognitions=[];
const context=vm.createContext({console,Event,EventTarget,CustomEvent,Float32Array,document,navigator:{userAgent:'Chrome/145'},setTimeout,clearTimeout,performance:{now:()=>now},requestAnimationFrame:fn=>{raf.set(++rafId,fn);return rafId;},cancelAnimationFrame:id=>raf.delete(id),ResizeObserver:class{observe(){}disconnect(){}},devicePixelRatio:1,matchMedia:()=>({matches:false}),addEventListener(){},Option:class extends Element{constructor(text,value){super();this.text=text;this.value=value;}},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}});
context.SpeechRecognition=class{start(){recognitions.push(this);this.onstart?.();}abort(){this.aborted=true;}};
const scripts=[...html.matchAll(/<script defer src="([^"]+)"/g)].map(m=>m[1]);
for(const script of scripts){assert(fs.existsSync(path.join(base,script)),script+' missing');if(script==='resources/app.js'){context.Starlight.Microphone=class{constructor(){this.ready=false;this.recording=false;this.stream={getAudioTracks:()=>[{clone:()=>({enabled:true,stop(){}})}]};}async open(){this.ready=true;}begin(){this.recording=true;}cancel(){this.recording=false;}snapshot(){return {samples:new Float32Array(0),sampleRate:16000};}};const Original=context.Starlight.DinosaurGame;context.Starlight.DinosaurGame=class extends Original{constructor(args){super(args);currentGame=this;}};}vm.runInContext(fs.readFileSync(path.join(base,script),'utf8'),context,{filename:script});}
const frame=()=>{now+=50;const callbacks=[...raf.values()];raf.clear();for(const fn of callbacks)fn(now);},click=id=>elements[id].dispatchEvent(new Event('click')),settle=()=>new Promise(resolve=>setImmediate(resolve));
async function start(kind,lesson='swedish'){const radio=radios.find(r=>r.value===kind);assert(radio,kind+' missing from menu');radio.dispatchEvent(new Event('change'));elements.lesson.value=lesson;elements.lesson.dispatchEvent(new Event('change'));click('start');await settle();assert.equal(elements['setup-error'].textContent,'');assert.equal(elements.play.hidden,false);frame();}
(async()=>{
 assert.equal(radios.length,6);assert.match(html,/<title>Skolarkaden<\/title>/);assert.doesNotMatch(html,/id="(?:queue-list|voice-toggle|live-speech|interim)"/);assert.match(html,/<details id="debug-panel"[^>]*>/);assert.doesNotMatch(html,/<details id="debug-panel"[^>]*\bopen\b/);
 elements.lesson.value='englishLong';elements.language.value='en-US';radios.find(r=>r.value==='food').dispatchEvent(new Event('change'));assert.equal(elements.lesson.value,'englishLong');assert.equal(elements.language.value,'en-US');elements.lesson.value='food';radios.find(r=>r.value==='city').dispatchEvent(new Event('change'));assert.equal(elements.lesson.value,'food');
assert(scripts.indexOf('resources/dinosaur.js')<scripts.indexOf('resources/app.js'));
 await start('dinosaur');assert.equal(elements['game-title'].textContent,'Hungrig dinosaurie');assert.equal(elements.play.dataset.game,'dinosaur');currentGame.spawnIn=10000;const p=currentGame.getTargets()[0];
 elements.answer.value=p.item.answer;elements['answer-form'].dispatchEvent(new Event('submit',{cancelable:true}));assert.equal(currentGame.queue.length,1);assert.equal(elements.answer.value,'');
 for(let i=0;i<500&&currentGame.hits<1;i++)frame();assert.equal(currentGame.hits,1);for(let i=0;i<4;i++)frame();assert.equal(elements.score.textContent,'1');assert.equal(elements.secondary.textContent,'');
 click('pause');assert.equal(currentGame.state,'paused');assert.equal(elements['pause-overlay'].hidden,false);const time=currentGame.elapsed;frame();assert.equal(currentGame.elapsed,time);click('resume');await settle();assert.equal(currentGame.state,'playing');
 currentGame.passed=40;currentGame.escaped=39;currentGame.spawned=40;frame();assert.equal(elements.answer.disabled,true);assert.equal(elements.pause.disabled,true);for(let i=0;i<60;i++)frame();assert.equal(elements['end-overlay'].hidden,false);assert.equal(elements['result-title'].textContent,'Mätt och belåten!');assert.match(elements['result-detail'].textContent,/1 uppätna.*39 gick vidare.*40 totalt/);
 click('again');await settle();assert.equal(currentGame.score,0);assert.equal(currentGame.passed,0);assert.equal(elements['end-overlay'].hidden,true);click('pause-menu');assert.equal(elements.menu.hidden,false);
 await start('dinosaur','letters');currentGame.spawnIn=10000;elements.answer.value=currentGame.getTargets()[0].item.answer;elements.answer.dispatchEvent(new Event('input'));assert.equal(currentGame.queue.length,1);assert.equal(elements.answer.value,'');assert.equal(elements['answer-form'].querySelector('[type=submit]'),null);click('pause-menu');
 assert.equal(elements.hints,undefined);await start('dinosaur','chinese');currentGame.spawnIn=10000;currentGame.walkSpeed=0;currentGame.runSpeed=0;const character=currentGame.getTargets()[0];
 while(currentGame.clock-character.appearedAt<4.8)frame();assert(!elements.targets.textContent.includes(character.item.hint));click('pause');for(let i=0;i<30;i++)frame();assert(!elements.targets.textContent.includes(character.item.hint));click('resume');await settle();
 while(currentGame.clock-character.appearedAt<5.2)frame();assert(elements.targets.textContent.includes(character.item.hint));click('pause-menu');
 for(const kind of ['city','food','garden','hive','paint']){await start(kind);frame();click('pause-menu');assert.equal(elements.menu.hidden,false);}
 elements['input-kind'].value='browser';await start('dinosaur');assert.equal(elements['input-dock'].hidden,true);assert(elements.answer.disabled);const heard=currentGame.getTargets()[0].item.answer;let r=recognitions.at(-1);r.onresult({results:[Object.assign([{transcript:heard,confidence:.9}],{isFinal:false})],resultIndex:0});assert.equal(currentGame.queue.items[0].text,heard);assert.match(elements['speech-log'].value,/PRELIMINÄR/);
 r.onerror({error:'network'});assert.equal(currentGame.state,'paused');assert.equal(elements['pause-overlay'].hidden,false);assert.match(elements['resume-error'].textContent,/nätverksanslutning/);click('resume');await settle();assert.equal(currentGame.state,'playing');assert.notEqual(recognitions.at(-1),r);click('pause-menu');elements['input-kind'].value='typing';await start('dinosaur');assert.equal(elements['input-dock'].hidden,false);assert.equal(elements.answer.disabled,false);click('pause-menu');
 console.log('PASS hidden voice UI, speech queue, visible fault pause/recovery, exercise persistence, branding, six local game scripts, dinosaur menu/start, typed queue, scoring HUD, pause/resume, celebration/results, replay, instant letters and switching to all five existing games.');
})().catch(e=>{console.error(e);process.exitCode=1;});
