/* DOM/Canvas stand-ins exercise the actual HTML script order and app wiring.
   This is a Node integration check, not a browser or microphone hardware test. */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const base=path.join(__dirname,'..'),html=fs.readFileSync(path.join(base,'index.html'),'utf8');
class CustomEvent extends Event{constructor(type,{detail}={}){super(type);this.detail=detail;}}
const context2d=new Proxy({},{get:(_,key)=>key==='measureText'?s=>({width:[...s].length*9}):key==='createLinearGradient'||key==='createRadialGradient'?()=>({addColorStop(){}}):()=>{}});
class Element extends EventTarget{
 constructor(){super();Object.assign(this,{value:'',textContent:'',text:'',hidden:false,disabled:false,checked:false,children:[],options:[],dataset:{},className:'',open:false});this.classList={add(){},remove(){},toggle(){}};}
 append(...items){this.children.push(...items);}replaceChildren(...items){this.children=[...items];}add(option){this.options.push(option);if(this.options.length===1)this.value=option.value;}
 closest(){return this.parent||(this.parent=new Element());}querySelector(selector){return this.noSubmit&&selector==='[type=submit]'?null:this.button||(this.button=new Element());}setAttribute(){}focus(){}select(){}remove(){}showModal(){this.open=true;}close(){this.open=false;this.dispatchEvent(new Event('close'));}
 getBoundingClientRect(){return {width:1000,height:700};}getContext(){return context2d;}
}
const elements={};for(const tag of html.match(/<[^>]+\bid="[^"]+"[^>]*>/g)||[]){const id=tag.match(/\bid="([^"]+)"/)[1],el=new Element();el.hidden=/\bhidden\b/.test(tag);el.checked=/\bchecked\b/.test(tag);elements[id]=el;}
for(const [,id,body] of html.matchAll(/<select[^>]*\bid="([^"]+)"[^>]*>([\s\S]*?)<\/select>/g))for(const [,value,text] of body.matchAll(/<option value="([^"]*)"[^>]*>([^<]*)<\/option>/g)){const option=new Element();option.value=value;option.text=text;elements[id].add(option);}
elements['answer-form'].noSubmit=true;
const radios=[...html.matchAll(/<input[^>]*name="game"[^>]*value="([^"]+)"[^>]*>/g)].map(([,value])=>Object.assign(new Element(),{value}));
const document=Object.assign(new EventTarget(),{hidden:false,body:new Element(),getElementById:id=>{assert(elements[id],'unknown DOM id '+id);return elements[id];},createElement:()=>new Element(),createDocumentFragment:()=>new Element(),querySelector:()=>null,querySelectorAll:selector=>selector==='[name=game]'?radios:[]});
const raf=new Map(),storage=new Map();let rafId=0,now=0,currentGame,currentMarshmallow,currentEgg,currentHome;const recognitions=[];
const context=vm.createContext({crypto:require('node:crypto').webcrypto,AbortController,fetch:async(url,options={})=>({ok:true,json:async()=>options.method==='POST'?{ok:true}:{scores:[],rank:1}}),console,Event,EventTarget,CustomEvent,Float32Array,document,navigator:{userAgent:'Chrome/145'},setTimeout,clearTimeout,performance:{now:()=>now},requestAnimationFrame:fn=>{raf.set(++rafId,fn);return rafId;},cancelAnimationFrame:id=>raf.delete(id),ResizeObserver:class{observe(){}disconnect(){}},devicePixelRatio:1,matchMedia:()=>({matches:false}),addEventListener(){},Option:class extends Element{constructor(text,value){super();this.text=text;this.value=value;}},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}});
context.SpeechRecognition=class{start(){recognitions.push(this);this.onstart?.();}abort(){this.aborted=true;}};
const scripts=[...html.matchAll(/<script defer src="([^"]+)"/g)].map(m=>m[1]);
for(const script of scripts){assert(fs.existsSync(path.join(base,script)),script+' missing');if(script==='resources/app.js'){context.Starlight.Microphone=class{constructor(){this.ready=false;this.recording=false;this.stream={getAudioTracks:()=>[{clone:()=>({enabled:true,stop(){}})}]};}async open(){this.ready=true;}begin(){this.recording=true;}cancel(){this.recording=false;}snapshot(){return {samples:new Float32Array(0),sampleRate:16000};}};const Original=context.Starlight.DinosaurGame;context.Starlight.DinosaurGame=class extends Original{constructor(args){super(args);currentGame=this;}};const Camp=context.Starlight.MarshmallowGame;context.Starlight.MarshmallowGame=class extends Camp{constructor(args){super(args);currentMarshmallow=this;}};const Home=context.Starlight.HomeGame;context.Starlight.HomeGame=class extends Home{constructor(args){super(args);currentHome=this;}};const Eggs=context.Starlight.EggGame;context.Starlight.EggGame=class extends Eggs{constructor(args){super(args);currentEgg=this;}};}vm.runInContext(fs.readFileSync(path.join(base,script),'utf8'),context,{filename:script});}
const frame=()=>{now+=50;const callbacks=[...raf.values()];raf.clear();for(const fn of callbacks)fn(now);},click=id=>elements[id].dispatchEvent(new Event('click')),settle=()=>new Promise(resolve=>setImmediate(resolve));
async function start(kind,lesson='swedish'){const radio=radios.find(r=>r.value===kind);assert(radio,kind+' missing from menu');radio.dispatchEvent(new Event('change'));elements.lesson.value=lesson;elements.lesson.dispatchEvent(new Event('change'));click('start');await settle();assert.equal(elements['setup-error'].textContent,'');assert.equal(elements.play.hidden,false);frame();}
(async()=>{
 assert.equal(radios.length,9);assert.match(html,/<title>Skolarkaden<\/title>/);assert.doesNotMatch(html,/id="(?:queue-list|voice-toggle|live-speech|interim)"/);assert.match(html,/<details id="debug-panel"[^>]*>/);assert.doesNotMatch(html,/<details id="debug-panel"[^>]*\bopen\b/);
 const SC=context.Starlight;assert.equal(elements.lesson.options.length,20);assert.deepEqual(elements.lesson.options.map(o=>o.text),Object.values(SC.modes).map(m=>m.name));
 assert.deepEqual([...html.match(/<div class="setup-grid">[\s\S]*?<div class="menu-bottom">/)[0].matchAll(/<select id="([^"]+)"/g)].map(m=>m[1]),['lesson','input-kind','language','pace']);
 assert.deepEqual(elements['input-kind'].options.map(o=>o.value),['typing','browser']);assert.deepEqual(elements.pace.options.map(o=>o.textContent),['Lätt','Medel','Svår']);assert(elements.language.disabled);
 elements['input-kind'].value='browser';elements['input-kind'].dispatchEvent(new Event('change'));assert.equal(elements.language.disabled,false);
 elements['input-kind'].value='typing';elements['input-kind'].dispatchEvent(new Event('change'));assert(elements.language.disabled);assert(!elements['install-language']);
 elements.lesson.value='englishLong';elements.language.value='en-US';radios.find(r=>r.value==='food').dispatchEvent(new Event('change'));assert.equal(elements.lesson.value,'englishLong');assert.equal(elements.language.value,'en-US');elements.lesson.value='math3';radios.find(r=>r.value==='city').dispatchEvent(new Event('change'));assert.equal(elements.lesson.value,'math3');
assert(scripts.indexOf('resources/dinosaur.js')<scripts.indexOf('resources/app.js'));
 await start('dinosaur');assert.equal(elements['game-title'].textContent,'Hungrig dinosaurie');assert.equal(elements.play.dataset.game,'dinosaur');currentGame.spawnIn=10000;const p=currentGame.getTargets()[0];
 elements.answer.value=p.item.answer;elements['answer-form'].dispatchEvent(new Event('submit',{cancelable:true}));assert.equal(currentGame.queue.length,1);assert.equal(elements.answer.value,'');
 for(let i=0;i<500&&currentGame.hits<1;i++)frame();assert.equal(currentGame.hits,1);for(let i=0;i<4;i++)frame();assert.equal(elements.score.textContent,'15');assert.equal(elements.secondary.textContent,'');
 click('pause');assert.equal(currentGame.state,'paused');assert.equal(elements['pause-overlay'].hidden,false);const time=currentGame.elapsed;frame();assert.equal(currentGame.elapsed,time);click('resume');await settle();assert.equal(currentGame.state,'playing');
 currentGame.passed=40;currentGame.escaped=39;currentGame.spawned=40;frame();assert.equal(elements.answer.disabled,true);assert.equal(elements.pause.disabled,true);for(let i=0;i<60;i++)frame();assert.equal(elements['end-overlay'].hidden,false);assert.equal(elements['result-title'].textContent,'Mätt och belåten!');assert.equal(elements['result-game'].textContent,'Hungrig dinosaurie');assert.match(elements['result-context'].textContent,/Lätt/);
 click('again');await settle();assert.equal(currentGame.score,0);assert.equal(currentGame.passed,0);assert.equal(elements['end-overlay'].hidden,true);click('pause-menu');assert.equal(elements.menu.hidden,false);
 await start('dinosaur','letters');currentGame.spawnIn=10000;elements.answer.value=currentGame.getTargets()[0].item.answer;elements.answer.dispatchEvent(new Event('input'));assert.equal(currentGame.queue.length,1);assert.equal(elements.answer.value,'');assert.equal(elements['answer-form'].querySelector('[type=submit]'),null);click('pause-menu');
 assert.equal(elements.hints,undefined);await start('dinosaur','chinese');currentGame.spawnIn=10000;currentGame.walkSpeed=0;currentGame.runSpeed=0;const character=currentGame.getTargets()[0];
 while(currentGame.clock-character.appearedAt<4.8)frame();assert(!elements.targets.textContent.includes(character.item.hint));click('pause');for(let i=0;i<30;i++)frame();assert(!elements.targets.textContent.includes(character.item.hint));click('resume');await settle();
 while(currentGame.clock-character.appearedAt<5.2)frame();assert(elements.targets.textContent.includes(character.item.hint));click('pause-menu');
 for(const kind of ['marshmallows','eggs','city','food','garden','hive','paint','home']){await start(kind);frame();assert.equal(elements.objective.closest('.hud-objective').hidden,['marshmallows','eggs'].includes(kind));if(['marshmallows','eggs'].includes(kind))assert.equal(elements.objective.textContent,'');else assert(elements.objective.textContent.length>0);click('pause-menu');assert.equal(elements.menu.hidden,false);}

 await start('home','letters');assert.equal(elements['game-title'].textContent,'Städa hemmet');assert.equal(elements.play.dataset.game,'home');assert.equal(currentHome.children,1);currentHome.chooseActivity=()=>false;currentHome.people.slice(1).forEach(p=>p.activity=null);const chore=currentHome.createTask('toys',{x:6,y:10.45});elements.answer.value=chore.item.answer;elements.answer.dispatchEvent(new Event('input'));assert.equal(currentHome.queue.length,1);for(let i=0;i<200&&currentHome.hits<1;i++)frame();assert.equal(currentHome.hits,1);for(let i=0;i<4;i++)frame();assert.equal(elements.score.textContent,'20');assert.equal(elements.objective.textContent,'1 / 40');click('pause');const homeClock=currentHome.clock;frame();assert.equal(currentHome.clock,homeClock);click('resume');await settle();assert.equal(currentHome.state,'playing');
 currentHome.cleaned=39;const finalChore=currentHome.createTask('toys',{x:6,y:10.45});elements.answer.value=finalChore.item.answer;elements.answer.dispatchEvent(new Event('input'));for(let i=0;i<500&&currentHome.state!=='won';i++)frame();assert.equal(currentHome.state,'won');assert.equal(elements['result-title'].textContent,'Skönt att vara klar!');assert.equal(elements['result-game'].textContent,'Städa hemmet');assert.equal(elements.answer.disabled,true);assert(currentHome.player.restAge>=2.5);assert.equal(SC.highscoreBoardKey({kind:'home',mode:'letters',pace:'gentle'}),'v1:home:letters:gentle');click('again');await settle();assert.equal(currentHome.cleaned,0);assert.equal(currentHome.score,0);click('pause-menu');
 elements['input-kind'].value='browser';await start('home','chinese');currentHome.chooseActivity=()=>false;currentHome.people.slice(1).forEach(p=>p.activity=null);const spokenChore=currentHome.createTask('toys',{x:6,y:10.45});spokenChore.item={label:'山',answer:'山',hint:'shān'};recognitions.at(-1).onresult({results:[Object.assign([{transcript:'衫',confidence:.9}],{isFinal:false})],resultIndex:0});assert.equal(currentHome.queue.length,1);for(let i=0;i<100&&!currentHome.hits;i++)frame();assert.equal(currentHome.hits,1);assert(elements['input-dock'].hidden);click('pause-menu');elements['input-kind'].value='typing';
 storage.set('starlight-queue-v2:eggs:letters:gentle','9999');
 await start('eggs','letters');assert.equal(elements['game-title'].textContent,'Äggröra');assert(elements.objective.closest('.hud-objective').hidden);currentEgg.eggs.forEach(e=>e.crackAt=10000);for(let i=0;i<150;i++)frame();const egg=currentEgg.eggs[0];egg.x=currentEgg.player.x+.07;egg.y=currentEgg.player.y;currentEgg.crack(egg);elements.answer.value=egg.item.answer;elements.answer.dispatchEvent(new Event('input'));assert.equal(currentEgg.queue.length,1);frame();assert.equal(egg.stage,'burning');click('pause');const eggClock=currentEgg.clock;for(let i=0;i<15;i++)frame();assert.equal(currentEgg.clock,eggClock);click('resume');await settle();for(let i=0;i<25;i++)frame();assert.equal(currentEgg.hits,1);assert.equal(elements.score.textContent,'10');
 currentEgg.eggs.forEach(e=>e.stage='dead');frame();assert(elements.answer.disabled);for(let i=0;i<65;i++)frame();assert.equal(elements['result-title'].textContent,'Skeppet är säkrat!');assert.equal(elements['result-game'].textContent,'Äggröra');assert.equal(storage.get('starlight-queue-v2:eggs:letters:gentle:v2'),'130');assert.equal(storage.get('starlight-queue-v2:eggs:letters:gentle'),'9999');click('again');await settle();assert.equal(currentEgg.hits,0);assert(currentEgg.eggs.every(e=>e.stage==='dormant'));currentEgg.player.status='dead';currentEgg.emit('player-down');frame();assert.equal(currentEgg.state,'playing');assert(elements.answer.disabled);click('pause');click('resume');await settle();assert(elements.answer.disabled,'dead player must not regain input on resume');currentEgg.people.forEach(p=>p.status='dead');frame();for(let i=0;i<65;i++)frame();assert.equal(elements['result-title'].textContent,'Rymdkrypen tog över.');click('end-menu');await settle();
 elements['input-kind'].value='browser';await start('eggs','chinese');currentEgg.eggs.forEach(e=>e.crackAt=10000);for(let i=0;i<150;i++)frame();const spokenEgg=currentEgg.eggs[0];spokenEgg.x=currentEgg.player.x+.07;spokenEgg.y=currentEgg.player.y;currentEgg.crack(spokenEgg);spokenEgg.item={answer:'十',label:'十',hint:'shí'};recognitions.at(-1).onresult({results:[Object.assign([{transcript:'是',confidence:.9}],{isFinal:false})],resultIndex:0});assert.equal(currentEgg.queue.length,1);frame();assert.equal(spokenEgg.stage,'burning');assert(elements['input-dock'].hidden);click('pause-menu');elements['input-kind'].value='typing';
 await start('marshmallows');assert.equal(elements['game-title'].textContent,'Marshmallows');assert.match(elements['setup-note'].textContent,/gyllene/);currentMarshmallow.spawnIn=10000;while(!currentMarshmallow.getTargets().length)frame();const sweet=currentMarshmallow.getTargets()[0];sweet.roast=.8;elements.answer.value=sweet.item.answer;elements['answer-form'].dispatchEvent(new Event('submit',{cancelable:true}));frame();assert.equal(currentMarshmallow.hits,1);for(let i=0;i<4;i++)frame();assert.equal(elements.score.textContent,'38');click('pause');const campClock=currentMarshmallow.clock;frame();assert.equal(currentMarshmallow.clock,campClock);click('resume');await settle();currentMarshmallow.elapsed=currentMarshmallow.duration-.05;frame();frame();assert.equal(elements.answer.disabled,true);assert.equal(elements.pause.disabled,true);for(let i=0;i<125;i++)frame();assert.equal(elements['result-title'].textContent,'God morgon!');assert.equal(elements['result-game'].textContent,'Marshmallows');click('again');await settle();assert.equal(currentMarshmallow.hits,0);assert.equal(currentMarshmallow.waste.length,0);click('pause-menu');
 elements['input-kind'].value='browser';await start('marshmallows');currentMarshmallow.spawnIn=10000;while(!currentMarshmallow.getTargets().length)frame();const spokenSweet=currentMarshmallow.getTargets()[0];spokenSweet.roast=.8;recognitions.at(-1).onresult({results:[Object.assign([{transcript:spokenSweet.item.answer,confidence:.9}],{isFinal:false})],resultIndex:0});assert.equal(currentMarshmallow.queue.length,1);frame();assert.equal(currentMarshmallow.hits,1);assert.equal(elements['input-dock'].hidden,true);click('pause-menu');
 elements['input-kind'].value='browser';await start('dinosaur');assert.equal(elements['input-dock'].hidden,true);assert(elements.answer.disabled);const heard=currentGame.getTargets()[0].item.answer;let r=recognitions.at(-1);r.onresult({results:[Object.assign([{transcript:heard,confidence:.9}],{isFinal:false})],resultIndex:0});assert.equal(currentGame.queue.items[0].text,heard);assert.match(elements['speech-log'].value,/PRELIMINÄR/);
 r.onerror({error:'network'});assert.equal(currentGame.state,'paused');assert.equal(elements['pause-overlay'].hidden,false);assert.match(elements['resume-error'].textContent,/nätverksanslutning/);click('resume');await settle();assert.equal(currentGame.state,'playing');assert.notEqual(recognitions.at(-1),r);click('pause-menu');elements['input-kind'].value='typing';await start('dinosaur');assert.equal(elements['input-dock'].hidden,false);assert.equal(elements.answer.disabled,false);click('pause-menu');
 console.log('PASS hidden voice UI, speech queue, visible fault pause/recovery, exercise persistence, branding, nine local game scripts, dinosaur menu/start, typed queue, scoring HUD, pause/resume, celebration/results, replay, instant letters and switching between all nine games, marshmallow timing, pause, dawn and replay; Äggröra typing/speech, player death, pause, victory/loss and replay; Städa hemmet keyboard/speech, HUD, pause, cleanup, scoreboard, resting and replay.');
})().catch(e=>{console.error(e);process.exitCode=1;});
