'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {DatabaseSync}=require('node:sqlite'),{webcrypto}=require('node:crypto');
const base=path.join(__dirname,'..'),read=file=>fs.readFileSync(path.join(base,file),'utf8');
const db=new DatabaseSync(':memory:');db.exec(read('cloudflare/schema.sql'));
const migration=new DatabaseSync(':memory:');migration.exec(read('cloudflare/schema.sql').replace('    settings_json TEXT,\n',''));
migration.prepare('INSERT INTO highscores(submission_id,leaderboard_key,player_name,score) VALUES(?,?,?,?)').run('existing','v1:home:letters:brave','ANONYM',70);
migration.exec(read('cloudflare/add-score-settings.sql'));assert.deepEqual({...migration.prepare('SELECT player_name,score,settings_json FROM highscores').get()},{player_name:'ANONYM',score:70,settings_json:null});migration.close();
// Execute the Worker's actual SQL with SQLite; only the D1 transport is adapted.
const DB={prepare(sql){let params=[];return {
  bind(...values){params=values;return this;},
  async run(){const result=db.prepare(sql).run(...params);return {meta:{changes:Number(result.changes)}};},
  async all(){return {results:db.prepare(sql).all(...params)};},
  async first(){return db.prepare(sql).get(...params)||null;}
};}};
const origin='https://jakobrogstadius.github.io',board='v2:city:swedish:gentle';
const payload=(extra={})=>({submission_id:webcrypto.randomUUID(),leaderboard_key:board,player_name:'Stefan',score:123,...extra});
let focused=null;
class Element extends EventTarget{
  constructor(){super();this.dataset={};this.value='';this.textContent='';this.children=[];this.open=false;}
  focus(){focused=this;}
  setSelectionRange(start,end){this.selectionStart=start;this.selectionEnd=end;}
  setAttribute(key,value){this[key]=value;}
  append(...items){this.children.push(...items);}replaceChildren(){this.children=[];}showModal(){this.open=true;}
  close(){this.open=false;this.dispatchEvent(new Event('close'));}
}
(async()=>{
  assert.equal(read('cloudflare/worker.mjs'),'// Generated by node cloudflare/build.cjs. Deploy this entire file.\n'+read('resources/highscore-policy.js')+'\n'+read('cloudflare/worker-source.mjs'),'deployable Worker must contain the current shared policy');
  const worker=(await import('../cloudflare/worker.mjs')).default;
  const call=(method,pathname='/scores',body,headers={})=>worker.fetch(new Request('https://example.workers.dev'+pathname,{
    method,headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':'192.0.2.10',...headers},
    ...(body===undefined?{}:{body:JSON.stringify(body)})}),{DB});
  assert.equal((await call('GET','/health')).status,200);
  const preflight=await call('OPTIONS');assert.equal(preflight.status,204);assert.equal(preflight.headers.get('Access-Control-Allow-Origin'),origin);
  assert.equal((await call('POST','/scores',payload(),{Origin:'https://unrelated.example'})).status,403);
  const settings={game_version:'v2',game:'city',exercise:'swedish',difficulty:'gentle',input_mode:'voice',spoken_language:'zh-TW',exercise_language:'zh-TW',uppercase:false,sound_enabled:true,reduced_motion:false,letter_keys:null};
  const first=payload({ip:'198.51.100.99',settings});
  assert.equal((await call('POST','/scores',first)).status,201);
  assert.equal(db.prepare('SELECT ip FROM highscores').get().ip,'192.0.2.10','ignore browser-supplied IP');
  assert.deepEqual(JSON.parse(db.prepare('SELECT settings_json FROM highscores').get().settings_json),settings,'every selected setting is retained without changing the score key');
  assert.equal((await call('POST','/scores',first)).status,200);
  assert.equal(db.prepare('SELECT count(*) AS n FROM highscores').get().n,1,'retry is idempotent');
  assert.equal((await call('POST','/scores',{...first,score:999})).status,409);
  assert.equal((await call('POST','/scores',{...first,settings:{...settings,input_mode:'keyboard'}})).status,409);
  for(const change of [{difficulty:'brave'},{spoken_language:'unexpected'},{uppercase:'yes'},{letter_keys:['a']}])assert.equal((await call('POST','/scores',payload({settings:{...settings,...change}}))).status,400);
  for(const score of [-1,1.5,'123',1000001])assert.equal((await call('POST','/scores',payload({score}))).status,400);
  for(const key of ['v1:city:swedish:sv-SE:typing:gentle','v1:city:swedish:gentle:','v1:bogus:swedish:gentle','v1:city:swedish:gentle']){
    assert.equal((await call('POST','/scores',payload({leaderboard_key:key}))).status,400);
  }
  const before=db.prepare('SELECT count(*) AS n FROM highscores').get().n;
  for(const player_name of ['FUCK','f.u.c.k','F1TT4','jävla','J A V L A','skitstövel','bitch','ta livet av dig','$h1t']){
    const result=await call('POST','/scores',payload({player_name}));assert.equal(result.status,200,player_name);assert.deepEqual(await result.json(),{ok:true});
  }
  assert.equal(db.prepare('SELECT count(*) AS n FROM highscores').get().n,before,'blocked names are silently discarded by the server');
  for(const player_name of ['Stefan','Susanne','Klasskompis','Åsa','Bosse','Stjärna','小明']){
    assert.equal(globalThis.SkolarkadenHighscorePolicy.isBannedName(player_name),false,player_name);
  }
  assert.equal((await call('POST','/scores',payload({player_name:'<img onerror=x>'}))).status,400);
  assert.equal((await call('POST','/scores',payload({player_name:'a'.repeat(3000)}))).status,413);
  // Separate boards and descending order. Add rows directly to avoid exhausting
  // the shared-address limit while filling a representative leaderboard.
  for(let i=0;i<25;i++)db.prepare('INSERT INTO highscores(submission_id,leaderboard_key,player_name,score,ip) VALUES(?,?,?,?,?)')
    .run(webcrypto.randomUUID(),board,'Spelare '+i,200+i,'192.0.2.1');
  await call('POST','/scores',payload({leaderboard_key:'v2:food:swedish:gentle',score:9999}));
  const scores=await (await call('GET','/scores?leaderboard='+board)).json();
  assert.equal(scores.scores.length,10);assert.equal(scores.scores[0].score,224);
  assert(scores.scores.every(row=>!('ip' in row)&&!('submission_id' in row)),'private fields never reach the public response');
  const rankData=await (await call('GET','/scores?leaderboard='+board+'&score=1')).json();assert.equal(rankData.rank,27);
  const tied=await (await call('GET','/scores?leaderboard='+board+'&score=224')).json();assert.equal(tied.rank,2);
  const own=await (await call('GET','/scores?leaderboard='+board+'&submission='+first.submission_id+'&score=123')).json();assert.equal(own.rank,26);assert.equal(own.saved,true);
  const winner=payload({score:999,player_name:'åsa'});assert.equal((await call('POST','/scores',winner)).status,201);
  const winnerBoard=await (await call('GET','/scores?leaderboard='+board+'&submission='+winner.submission_id+'&score=999')).json();assert.equal(winnerBoard.capabilities.game_boards,true);assert.equal(winnerBoard.rank,1);assert.equal(winnerBoard.scores[0].is_player,1);assert.equal(winnerBoard.scores[0].player_name,'ÅSA');
  assert.equal((await call('POST','/scores',payload({player_name:'ABCDEFGHIJK'}))).status,400);
  const anon=payload({player_name:''});assert.equal((await call('POST','/scores',anon)).status,201);assert.equal(db.prepare('SELECT player_name FROM highscores WHERE submission_id=?').get(anon.submission_id).player_name,'ANONYM');
  // Existing exercise/difficulty rows share one game ranking without mixing games or versions.
  const medium=payload({leaderboard_key:'v2:city:swedish:steady',score:1200}),hard=payload({leaderboard_key:'v2:city:swedish:brave',score:1100});
  await call('POST','/scores',medium);await call('POST','/scores',hard);
  db.prepare('INSERT INTO highscores(submission_id,leaderboard_key,player_name,score) VALUES(?,?,?,?)').run(webcrypto.randomUUID(),'v1:city:swedish:brave','OLD',9000);
  await call('POST','/scores',payload({leaderboard_key:'v2:city:english:brave',score:8000}));
  for(const key of ['v2:city','v2:city:swedish:gentle','v2:city:swedish:steady','v2:city:swedish:brave']){
    const mixed=await (await call('GET','/scores?leaderboard='+key+'&score=999&submission='+winner.submission_id)).json();
    assert.equal(mixed.rank,4);assert.deepEqual(mixed.scores.slice(0,4).map(r=>r.difficulty),['brave','steady','brave','gentle']);assert.deepEqual(mixed.scores.slice(0,4).map(r=>r.exercise),['english','swedish','swedish','swedish']);assert.equal(mixed.scores[3].is_player,1);
  }
  assert.equal((await (await call('GET','/scores?leaderboard=v2:city&score=1100')).json()).rank,4);
  for(const key of ['v2:city:swedish','v2:city:english','v2:city:swedish:bogus','v2:city:swedish:brave:extra','v1:city:swedish'])assert.equal((await call('GET','/scores?leaderboard='+key)).status,400);
  const plan=db.prepare('EXPLAIN QUERY PLAN SELECT player_name,score,created_at FROM highscores WHERE leaderboard_key IN (?,?,?) ORDER BY score DESC,created_at ASC,submission_id ASC LIMIT 10').all(board,'v2:city:swedish:steady','v2:city:swedish:brave');
  assert(plan.some(row=>row.detail.includes('idx_highscores_leaderboard')));
  db.prepare('UPDATE score_rate_limits SET attempts=120').run();
  assert.equal((await call('POST','/scores',payload())).status,429);
  db.prepare('UPDATE score_rate_limits SET window_start=0').run();
  assert.equal((await call('POST','/scores',payload())).status,201,'counter resets in a new window');
  // Browser module: no POST for banned names, identical visible success; retries
  // reuse one ID/payload and results remain tied to the completed game's board.
  const elements=new Map(),get=id=>{if(!elements.has(id))elements.set(id,new Element());return elements.get(id);};
  get('pace').options=Array.from(read('index.html').match(/<select id="pace">([\s\S]*?)<\/select>/)[1].matchAll(/<option value="([^"]+)">([^<]+)<\/option>/g),match=>({value:match[1],textContent:match[2]}));
  const nicknameStorage=new Map([['skolarkaden-nickname-v1','OLD NAME']]);
  let posts=[],failOnce=false,unsupported=false,legacyBoards=null,boardData={scores:[],rank:1};
  const context=vm.createContext({Starlight:{},console,crypto:webcrypto,Event,EventTarget,setTimeout,clearTimeout,AbortController,
    document:{get activeElement(){return focused;},getElementById:get,createElement:()=>new Element()},localStorage:{getItem:key=>nicknameStorage.get(key),setItem:(key,value)=>nicknameStorage.set(key,value),removeItem:key=>nicknameStorage.delete(key)},
    fetch:async(url,options)=>{if(options.method==='POST'){posts.push(JSON.parse(options.body));if(failOnce){failOnce=false;throw new Error('network');}return Response.json({ok:true});}if(legacyBoards){const key=new URL(url).searchParams.get('leaderboard');assert.equal(key.split(':').length,4);return Response.json({leaderboard:key,scores:key.split(':')[2]==='swedish'?legacyBoards[key.split(':')[3]]:[]});}return unsupported?Response.json({error:'invalid_leaderboard'},{status:400}):Response.json(boardData);}});
  vm.runInContext(read('resources/data.js'),context);
  vm.runInContext(read('resources/highscore-policy.js'),context);vm.runInContext(read('resources/highscores.js'),context);
  const selection={kind:'city',mode:'swedish',pace:'gentle',input:'typing',lang:'sv-SE',label:'Meteorregn'};
  assert.equal(context.Starlight.highscoreBoardKey(selection),'v2:city');
  assert.equal(context.Starlight.highscoreBoardKey({...selection,kind:'eggs'}),'v2:eggs');
  for(const [game,version] of Object.entries(context.SkolarkadenHighscorePolicy.versions))assert.equal(version,game==='home'?'v1':'v2');
  assert.equal((await call('POST','/scores',payload({leaderboard_key:'v2:eggs:swedish:gentle'}))).status,201);
  assert.equal((await call('POST','/scores',payload({leaderboard_key:'v1:eggs:swedish:gentle'}))).status,400);
  assert.equal(context.Starlight.highscoreBoardKey({...selection,kind:'home'}),'v1:home');
  assert.equal((await call('POST','/scores',payload({leaderboard_key:'v1:home:swedish:gentle',score:20}))).status,201);
  assert.equal((await call('GET','/scores?leaderboard=v1:home:swedish:gentle')).status,200);
  assert.equal((await call('POST','/scores',payload({leaderboard_key:'v2:home:swedish:gentle',score:20}))).status,400);
  assert.equal(context.Starlight.highscoreBoardKey({...selection,input:'browser',lang:'zh-TW'}),'v2:city');
  assert.equal(context.Starlight.highscoreBoardKey({...selection,mode:'english'}),context.Starlight.highscoreBoardKey(selection));
  assert.equal(context.Starlight.highscoreBoardKey({...selection,pace:'brave'}),context.Starlight.highscoreBoardKey(selection));
  const ui=new context.Starlight.Highscores({getSelection:()=>selection});
  // Both boards render the menu's complete labels, with casing handled by CSS.
  for(const listId of ['scores-list','end-scores-list']){
    const list=get(listId);
    for(const [exercise,mode] of Object.entries(context.Starlight.modes)){
      for(const option of get('pace').options){
        list.replaceChildren();ui.row(list,{player_name:'TEST',score:1,exercise,difficulty:option.value},1);
        assert.equal(list.children[0].children[2].textContent,mode.name);
        assert.equal(list.children[0].children[3].textContent,option.textContent);
      }
    }
    list.replaceChildren();
  }
  legacyBoards={gentle:[{score:200,player_name:'A'},{score:80,player_name:'B'}],steady:[{score:210,player_name:'C'}],brave:[{score:300,player_name:'D'}]};
  ui.begin(selection);ui.finish(150);await ui.open(selection,ui.result);assert.deepEqual([...ui.data.scores].map(r=>r.score),[300,210,200,80]);assert.equal(ui.data.rank,4);assert.deepEqual([...ui.data.scores].map(r=>r.difficulty),['brave','steady','gentle','gentle']);assert.equal(focused,get('score-name'));assert.equal(posts.length,0);
  get('score-name').value='ÅS';get('score-name').setSelectionRange(1,1);await ui.load(ui.view);assert.equal(focused,get('score-name'));assert.equal(get('score-name').selectionStart,1);get('again').focus();await ui.load(ui.view);assert.equal(focused,get('again'),'loading must not steal focus after Tab');
  legacyBoards.brave=Array.from({length:10},()=>({score:300,player_name:'D'}));await ui.load(ui.view);assert.equal(ui.data.rank,null,'limited legacy rows cannot establish a low rank');legacyBoards=null;
  ui.begin(selection);
  ui.begin(selection);unsupported=true;await ui.open({...selection,kind:'home'});assert.equal(get('scores-status').textContent,'Topplistan är inte redo för det här spelet ännu.');unsupported=false;
  assert.equal(get('score-name').value,'');assert.equal(nicknameStorage.size,0,'discard legacy remembered names');
  ui.begin(selection);ui.finish(200);ui.open(selection,ui.result);get('score-name').value='f.u.c.k';await ui.submit();
  assert.equal(posts.length,0);assert.equal(get('score-status').textContent,'Resultatet är sparat.');
  ui.begin(selection);ui.finish(300);ui.open(selection,ui.result);get('score-name').value='Åsa';failOnce=true;await ui.submit();
  assert.equal(ui.result.saved,false);const pendingId=ui.result.id;
  get('score-name').value='Someone else';await ui.submit();
  assert.equal(posts.length,2);assert.deepEqual(posts[0],posts[1]);assert.equal(posts[1].submission_id,pendingId);assert.equal(posts[1].leaderboard_key,board,'store the played difficulty');assert.equal(ui.result.saved,true);
  assert.equal(posts[1].settings.input_mode,'keyboard');assert.equal(posts[1].settings.spoken_language,'sv-SE');assert.equal(posts[1].settings.game,'city');
  await ui.submit();assert.equal(posts.length,2,'saved result cannot be submitted again');
  // Display top ten plus the actual rank below them; never post merely for opening.
  boardData={scores:Array.from({length:10},(_,i)=>({player_name:'PLAYER',score:1000-i})),rank:38,saved:false};
  ui.begin(selection);ui.finish(12);await ui.open(selection,ui.result);assert.equal(get('score-name').value,'','new round never reuses the previous name');assert.equal(nicknameStorage.size,0,'submitted names are not remembered');assert.equal(posts.length,2);assert.equal(get('end-scores-list').children.length,11);assert.equal(get('end-scores-list').children[10].children[0].textContent,'38');
  boardData={...boardData,rank:3};await ui.load(ui.view);assert.equal(get('end-scores-list').children.length,10);assert.equal(get('end-scores-list').children[2].className,'board-row player-row');assert.equal(get('end-scores-list').children[2].children[3].textContent,'Lätt');assert.equal(get('end-scores-list').children[2].children[2].textContent,'Svenska ord - korta');assert.equal(get('end-scores-list').children[2].children[4].textContent,'12');
  let continued=false;await ui.leave(()=>{continued=true;});assert(continued);assert.equal(posts.at(-1).player_name,'ANONYM');
  ui.begin(selection);ui.finish(1);await ui.open(selection,ui.result);const count=posts.length;ui.dismiss();assert.equal(posts.length,count,'closing without action never posts');
  ui.begin(selection);ui.finish(7);await ui.open(selection,ui.result);get('score-name').value='BOSSE';failOnce=true;continued=false;await ui.leave(()=>{continued=true;});assert.equal(continued,false);assert.equal(ui.result.saved,false);await ui.leave(()=>{continued=true;});assert(continued);assert.deepEqual(posts.at(-1),posts.at(-2));
  // A saved top-ten player occupies exactly one ranked row, even with duplicate names/scores.
  boardData={scores:Array.from({length:10},(_,i)=>({player_name:'BOSSE',score:99,is_player:i===4})),rank:5,saved:true};
  await ui.open(selection,ui.result);assert.equal(get('end-scores-list').children.length,10);assert.equal(get('end-scores-list').children.filter(row=>row.className.includes('player-row')).length,1);
  const configured={...selection,kind:'home',mode:'letters',pace:'brave',input:'browser',lang:'sv-SE',spokenLanguage:'sv-SE',uppercase:true,letterKeys:['å','ä','ö'],soundEnabled:false,reducedMotion:true};
  ui.begin(configured);configured.letterKeys.push('x');ui.finish(250);await ui.open(configured,ui.result);get('score-name').value='TEST';await ui.submit();
  const sent=posts.at(-1);assert.deepEqual(sent.settings.letter_keys,['å','ä','ö'],'snapshot actual practice keys at round start');assert.equal(sent.settings.input_mode,'voice');assert.equal(sent.settings.uppercase,true);assert.equal(sent.settings.sound_enabled,false);assert.equal(sent.settings.reduced_motion,true);
  assert.equal((await call('POST','/scores',sent)).status,201,'the actual frontend payload is accepted by the Worker');assert.deepEqual(JSON.parse(db.prepare('SELECT settings_json FROM highscores WHERE submission_id=?').get(sent.submission_id).settings_json),sent.settings);
  // Popularity uses every saved round, not just the top ten or non-anonymous names.
  db.exec('DELETE FROM highscores');
  const emptyStats=await (await call('GET','/stats?group=games')).json();
  assert.equal(emptyStats.entries.length,9);assert(emptyStats.entries.every(r=>r.plays===0&&r.score===null&&r.player_name===null));
  const fixtures=[
    ['v2:city:swedish:gentle','ANONYM',10],
    ['v2:city:swedish:steady','TOP CITY',100],
    ['v2:city:swedish:brave','TIED',100],
    ['v2:city:english:gentle','EN WIN',80],
    ['v1:city:swedish:brave','OLD',9999],
    ['v1:city:math:brave','RETIRED',10000],
    ['v2:city:swedish:gentle','LATER',100,'2026-02-01'],
    ['v2:food:swedish:brave','FOOD WIN',500],
    ['v2:food:english:steady','FOOD EN',60],
    ['v1:garden:swedish:gentle','OLD ONLY',1000],
    ['vgarbage:city:swedish:gentle','INVALID',100000],
    ['v2:city:swedish:gentle:extra','EXTRA',100000],
    ['v2:bogus:swedish:gentle','UNKNOWN',100000],
  ];
  fixtures.forEach(([key,name,score,date='2026-01-01'],i)=>db.prepare('INSERT INTO highscores(submission_id,leaderboard_key,player_name,score,created_at,ip) VALUES(?,?,?,?,?,?)')
    .run('00000000-0000-4000-8000-'+String(i).padStart(12,'0'),key,name,score,date,'192.0.2.123'));
  const statsResponse=await call('GET','/stats?group=games'),gameStats=await statsResponse.json();
  assert.equal(statsResponse.headers.get('Cache-Control'),'public, max-age=60');
  assert.equal(statsResponse.headers.get('Access-Control-Allow-Origin'),origin);
  assert.deepEqual(gameStats.entries.slice(0,3),[
    {id:'city',plays:7,player_name:'TOP CITY',score:100},
    {id:'food',plays:2,player_name:'FOOD WIN',score:500},
    {id:'garden',plays:1,player_name:null,score:null}
  ]);
  assert.deepEqual(Object.keys(gameStats.entries[0]).sort(),['id','player_name','plays','score'],'only aggregate public fields');
  const exerciseStats=await (await call('GET','/stats?group=exercises')).json();
  assert.equal(exerciseStats.entries.length,Object.keys(context.Starlight.modes).length);
  assert.deepEqual(exerciseStats.entries.slice(0,2),[
    {id:'swedish',plays:7,player_name:null,score:null,rating:null},
    {id:'english',plays:2,player_name:null,score:null,rating:null}
  ]);
  assert.equal(exerciseStats.ranking_method,'top-five-game-percentiles-v1');
  assert.equal((await (await call('GET','/health')).json()).capabilities.exercise_ratings,1);
  assert.equal(exerciseStats.entries[2].id,'letters','zero-count ties follow menu order');
  assert.equal((await call('GET','/stats?group=wrong')).status,400);
  assert.equal((await call('POST','/stats?group=games',{})).status,405);
  assert.equal((await call('OPTIONS','/stats')).status,204);
  assert.equal((await call('GET','/stats?group=games',undefined,{Origin:'https://unrelated.example'})).status,403);
  assert.equal((await (await call('GET','/health')).json()).capabilities.popularity_boards,1);
  db.close();console.log('PASS highscores: real SQLite, privacy, filtering, ranking, CORS, limits, keys, browser submission, retries and popularity aggregates.');
})().catch(error=>{console.error(error);process.exitCode=1;});
