'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {DatabaseSync}=require('node:sqlite'),{webcrypto}=require('node:crypto');
const base=path.join(__dirname,'..'),read=file=>fs.readFileSync(path.join(base,file),'utf8');
const db=new DatabaseSync(':memory:');db.exec(read('cloudflare/schema.sql'));
// Execute the Worker's actual SQL with SQLite; only the D1 transport is adapted.
const DB={prepare(sql){let params=[];return {
  bind(...values){params=values;return this;},
  async run(){const result=db.prepare(sql).run(...params);return {meta:{changes:Number(result.changes)}};},
  async all(){return {results:db.prepare(sql).all(...params)};},
  async first(){return db.prepare(sql).get(...params)||null;}
};}};
const origin='https://jakobrogstadius.github.io',board='v2:city:swedish:gentle';
const payload=(extra={})=>({submission_id:webcrypto.randomUUID(),leaderboard_key:board,player_name:'Stefan',score:123,...extra});
class Element extends EventTarget{
  constructor(){super();this.value='';this.textContent='';this.children=[];this.open=false;}
  append(...items){this.children.push(...items);}replaceChildren(){this.children=[];}showModal(){this.open=true;}
  close(){this.open=false;this.dispatchEvent(new Event('close'));}
}
(async()=>{
  assert.equal(read('cloudflare/worker.mjs'),'// Generated by node cloudflare/build.cjs. Deploy this entire file.\n'+read('resources/highscore-policy.js')+'\n'+read('cloudflare/worker-source.mjs'),'deployable Worker must contain the current shared policy');
  const worker=(await import('../cloudflare/worker.mjs')).default;
  const call=(method,pathname='/scores',body,headers={})=>worker.fetch(new Request('https://example.workers.dev'+pathname,{
    method,headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':'192.0.2.10',...headers},
    ...(body===undefined?{}:{body:JSON.stringify(body)})}),{DB});
  assert.equal((await call('GET','/health')).status,200);
  const preflight=await call('OPTIONS');assert.equal(preflight.status,204);assert.equal(preflight.headers.get('Access-Control-Allow-Origin'),origin);
  assert.equal((await call('POST','/scores',payload(),{Origin:'https://unrelated.example'})).status,403);
  const first=payload({ip:'198.51.100.99'});
  assert.equal((await call('POST','/scores',first)).status,201);
  assert.equal(db.prepare('SELECT ip FROM highscores').get().ip,'192.0.2.10','ignore browser-supplied IP');
  assert.equal((await call('POST','/scores',first)).status,200);
  assert.equal(db.prepare('SELECT count(*) AS n FROM highscores').get().n,1,'retry is idempotent');
  assert.equal((await call('POST','/scores',{...first,score:999})).status,409);
  for(const score of [-1,1.5,'123',1000001])assert.equal((await call('POST','/scores',payload({score}))).status,400);
  for(const key of ['v1:city:swedish:sv-SE:typing:gentle','v1:city:swedish:gentle:','v1:bogus:swedish:gentle','v1:city:swedish:gentle']){
    assert.equal((await call('POST','/scores',payload({leaderboard_key:key}))).status,400);
  }
  const before=db.prepare('SELECT count(*) AS n FROM highscores').get().n;
  for(const player_name of ['FUCK','f.u.c.k','F1TT4','jävla','J A V L A','skitstövel','bitch','ta livet av dig','$h1t']){
    const result=await call('POST','/scores',payload({player_name}));assert.equal(result.status,200,player_name);assert.deepEqual(await result.json(),{ok:true});
  }
  assert.equal(db.prepare('SELECT count(*) AS n FROM highscores').get().n,before,'blocked names are silently discarded by the server');
  for(const player_name of ['Stefan','Susanne','Klasskompis','Åsa','Bosse','Stjärna','小明']){
    assert.equal(globalThis.SkolarkadenHighscorePolicy.isBannedName(player_name),false,player_name);
  }
  assert.equal((await call('POST','/scores',payload({player_name:'<img onerror=x>'}))).status,400);
  assert.equal((await call('POST','/scores',payload({player_name:'a'.repeat(3000)}))).status,413);
  // Separate boards and descending order. Add rows directly to avoid exhausting
  // the shared-address limit while filling a representative leaderboard.
  for(let i=0;i<25;i++)db.prepare('INSERT INTO highscores(submission_id,leaderboard_key,player_name,score,ip) VALUES(?,?,?,?,?)')
    .run(webcrypto.randomUUID(),board,'Spelare '+i,200+i,'192.0.2.1');
  await call('POST','/scores',payload({leaderboard_key:'v2:food:swedish:gentle',score:9999}));
  const scores=await (await call('GET','/scores?leaderboard='+board)).json();
  assert.equal(scores.scores.length,20);assert.equal(scores.scores[0].score,224);
  assert(scores.scores.every(row=>!('ip' in row)&&!('submission_id' in row)),'private fields never reach the public response');
  const plan=db.prepare('EXPLAIN QUERY PLAN SELECT player_name,score,created_at FROM highscores WHERE leaderboard_key=? ORDER BY score DESC,created_at ASC LIMIT 20').all(board);
  assert(plan.some(row=>row.detail.includes('idx_highscores_leaderboard')));
  db.prepare('UPDATE score_rate_limits SET attempts=120').run();
  assert.equal((await call('POST','/scores',payload())).status,429);
  db.prepare('UPDATE score_rate_limits SET window_start=0').run();
  assert.equal((await call('POST','/scores',payload())).status,201,'counter resets in a new window');
  // Browser module: no POST for banned names, identical visible success; retries
  // reuse one ID/payload and results remain tied to the completed game's board.
  const elements=new Map(),get=id=>{if(!elements.has(id))elements.set(id,new Element());return elements.get(id);};
  let posts=[],failOnce=false;
  const context=vm.createContext({Starlight:{},console,crypto:webcrypto,Event,EventTarget,setTimeout,clearTimeout,AbortController,
    document:{getElementById:get,createElement:()=>new Element()},localStorage:{getItem:()=>'',setItem(){}},
    fetch:async(url,options)=>{if(options.method==='POST'){posts.push(JSON.parse(options.body));if(failOnce){failOnce=false;throw new Error('network');}return Response.json({ok:true});}return Response.json({scores:[]});}});
  vm.runInContext(read('resources/highscore-policy.js'),context);vm.runInContext(read('resources/highscores.js'),context);
  const selection={kind:'city',mode:'swedish',pace:'gentle',input:'typing',lang:'sv-SE',label:'Meteorregn'};
  assert.equal(context.Starlight.highscoreBoardKey(selection),board);
  assert.equal(context.Starlight.highscoreBoardKey({...selection,kind:'eggs'}),'v2:eggs:swedish:gentle');
  for(const [game,version] of Object.entries(context.SkolarkadenHighscorePolicy.versions))assert.equal(version,['eggs','city','food','garden'].includes(game)?'v2':'v1');
  assert.equal((await call('POST','/scores',payload({leaderboard_key:'v2:eggs:swedish:gentle'}))).status,201);
  assert.equal((await call('POST','/scores',payload({leaderboard_key:'v1:eggs:swedish:gentle'}))).status,400);
  assert.equal(context.Starlight.highscoreBoardKey({...selection,input:'browser',lang:'zh-TW'}),board);
  const ui=new context.Starlight.Highscores({getSelection:()=>selection});
  ui.begin(selection);ui.finish(200);ui.open(selection,ui.result);get('score-name').value='f.u.c.k';await ui.submit();
  assert.equal(posts.length,0);assert.equal(get('score-status').textContent,'Resultatet är sparat.');
  ui.begin(selection);ui.finish(300);ui.open(selection,ui.result);get('score-name').value='Åsa';failOnce=true;await ui.submit();
  assert.equal(ui.result.saved,false);const pendingId=ui.result.id;
  get('score-name').value='Someone else';await ui.submit();
  assert.equal(posts.length,2);assert.deepEqual(posts[0],posts[1]);assert.equal(posts[1].submission_id,pendingId);assert.equal(ui.result.saved,true);
  await ui.submit();assert.equal(posts.length,2,'saved result cannot be submitted again');
  db.close();console.log('PASS highscores: real SQLite, privacy, filtering, ranking, CORS, limits, keys, browser submission and retries.');
})().catch(error=>{console.error(error);process.exitCode=1;});
