'use strict';const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const ctx=vm.createContext({});for(const name of ['pinyin','data','speech'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../resources/'+name+'.js'),'utf8'),ctx);
const SC=ctx.Starlight,result=(text,isFinal=false)=>Object.assign([{transcript:text}],{isFinal});let checks=0;
function test(name,fn){fn();checks++;console.log('PASS '+name);}
function harness(lesson='swedish',language='sv-SE',words=['hund','mat','katt']){
 const state={lesson,language,candidates:words.map(answer=>({answer,aliases:[]}))},out=[],events=[];
 return {state,out,events,stream:new SC.SpeechStream({getContext:()=>state,enqueue:text=>out.push(text),trace:(type,data)=>events.push({type,...data})})};
}
test('Expected interim words are immediate; identical callbacks and finalization do not duplicate',()=>{const h=harness();h.stream.update([result('hund')]);assert.deepEqual(h.out,['hund']);h.state.candidates=h.state.candidates.filter(t=>t.answer!=='hund');h.stream.update([result('hund mat')]);h.stream.update([result('hund mat')]);h.stream.update([result('Hund mat.',true)]);assert.deepEqual(h.out,['hund','mat']);});
test('Unknown leading words keep their order; incomplete unmatched suffix waits for final',()=>{const h=harness();h.stream.update([result('eh hund ka')]);assert.deepEqual(h.out,['eh','hund']);h.stream.update([result('eh hund katt')]);assert.deepEqual(h.out,['eh','hund','katt']);h.stream.update([result('eh hund katt felord',true)]);assert.deepEqual(h.out,['eh','hund','katt','felord']);});
test('Revisions, temporary withdrawal and result-boundary changes do not resend early words',()=>{const h=harness();h.stream.update([result('hund katt')]);h.stream.update([result('hund')]);h.stream.update([]);h.stream.update([result('hund',true),result('katt')]);h.stream.update([result('hund',true),result('katt',true)]);assert.deepEqual(h.out,['hund','katt']);h.stream.update([result('hund',true),result('katt',true),result('katt',true)]);assert.deepEqual(h.out,['hund','katt','katt']);});
test('An empty final result retires withdrawn tokens so the next utterance can repeat them',()=>{const h=harness();h.stream.update([result('hund')]);h.stream.update([result('',true)]);h.stream.update([result('',true),result('hund',true)]);assert.deepEqual(h.out,['hund','hund']);});
test('A revised already-sent span logs a correction rather than starting another action',()=>{const h=harness();h.stream.update([result('hund')]);h.stream.update([result('katt',true)]);assert.deepEqual(h.out,['hund']);assert(h.events.some(e=>e.type==='revision'&&e.previous==='hund'&&e.text==='katt'));});
test('A correction updates a waiting queue entry but cannot rewrite an already-started job',()=>{
 const pending=[],context={lesson:'math',language:'en-US',candidates:[{answer:'2'},{answer:'20'}]},stream=new SC.SpeechStream({getContext:()=>context,enqueue:text=>{const entry={text};pending.push(entry);return entry;},revise:(entry,text)=>{if(!pending.includes(entry))return false;entry.text=text;return true;}});
 stream.update([result('two')]);stream.update([result('twenty')]);assert.equal(pending.length,1);assert.equal(pending[0].text,'twenty');const cooking=pending.shift();stream.update([result('2',true)]);assert.equal(cooking.text,'twenty');assert.equal(pending.length,0);
});
test('Two- and three-part Swedish compounds split only against available targets',()=>{const h=harness();h.stream.update([result('HUNDMAT! kattmatHUND',true)]);assert.deepEqual(h.out,['HUND','MAT!','katt','mat','HUND']);const no=harness('swedish','sv-SE',['hund']);no.stream.update([result('hundmat',true)]);assert.deepEqual(no.out,['hundmat']);const english=harness('english','en-US',['hund','mat']);english.stream.update([result('hundmat',true)]);assert.deepEqual(english.out,['hundmat']);});
test('A word joined after an early submission splits without resubmitting the consumed prefix',()=>{const h=harness();h.stream.update([result('hund')]);h.state.candidates=h.state.candidates.filter(t=>t.answer!=='hund');h.stream.update([result('hundmat')]);assert.deepEqual(h.out,['hund','mat']);h.state.candidates=[];h.stream.update([result('Hundmat.',true)]);assert.deepEqual(h.out,['hund','mat']);});
test('An expected long compound wins over splitting; number games never use Swedish word splitting',()=>{const h=harness('swedishLong','sv-SE',['hund','mat','hundmat']);h.stream.update([result('hundmat')]);assert.deepEqual(h.out,['hundmat']);assert.deepEqual(Array.from(SC.splitSwedish('etttvå',{lesson:'math',language:'sv-SE',candidates:[{answer:'1'},{answer:'2'}]})),['etttvå']);});
test('Speech-only homophones cover words and letters without accepting misspellings in typing',()=>{for(const text of ['see','sea','c','“SEE!”'])assert(SC.matches(text,{answer:'sea'},'english','en-US','speech'),text);assert(!SC.matches('see',{answer:'sea'},'english','en-US','text'));assert(!SC.matches('cat',{answer:'car'},'english','en-US','speech'));assert(SC.matches('flour',{answer:'flower'},'englishLong','en-US','speech'));assert(SC.matches('sea',{answer:'c'},'letters','en-US','speech'));const h=harness('english','en-US',['sea']);h.stream.update([result('see')]);h.stream.update([result('sea',true)]);assert.deepEqual(h.out,['see']);});
test('Number forms 0–20 round-trip in Swedish, English and both Chinese locales',()=>{for(const lang of ['sv-SE','en-US','zh-CN','zh-TW'])for(let n=0;n<=20;n++){for(const form of [String(n),String(n).padStart(2,'0'),n+'.0',n+',00',SC.numberName(n,lang)])assert(SC.matches(form,{answer:String(n)},'math',lang,'speech'),lang+' '+form);for(const [word,value] of Object.entries(SC.numberWords[lang]))assert(SC.matches(word,{answer:String(value)},'math',lang,'speech'));}assert(SC.matches('兩',{answer:'2'},'math','zh-TW','speech'));assert(SC.matches('２',{answer:'2'},'math','sv-SE','speech'));});
test('Strict numbers reject junk, fractions, negatives and out-of-range values',()=>{for(const v of ['2cats','-2','−2','2.5','2,5','22','2e0','1/2','minus two','two point five'])for(let n=0;n<=20;n++)assert(!SC.matches(v,{answer:String(n)},'math','en-US','speech'),v);for(const [v,n] of [['too',2],['to',2],['for',4],['ate',8],['won',1],['oh',0]]){assert(SC.matches(v,{answer:String(n)},'math','en-US','speech'));assert(!SC.matches(v,{answer:String(n)},'math','en-US','text'));}});
test('Math streaming accepts numbers early, reconciles words to digits, and groups decimal/negative phrases',()=>{const h=harness('math','en-US',['2','4','8']);h.stream.update([result('two for eight')]);assert.deepEqual(h.out,['two','for','eight']);h.stream.update([result('2 4 8',true)]);assert.deepEqual(h.out,['two','for','eight']);const bad=harness('math','en-US',['2','5']);bad.stream.update([result('minus two two point five',true)]);assert.deepEqual(bad.out,['minus two','two point five']);});
test('Letter names containing spaces are one command; literal repeated words remain separate',()=>{const h=harness('letters','en-US',['w','c']);h.stream.update([result('double you see see',true)]);assert.deepEqual(h.out,['double you','see','see']);const s=harness('letters','sv-SE',['w']);s.stream.update([result('dubbel ve',true)]);assert.deepEqual(s.out,['dubbel ve']);});
test('Mandarin digit runs queue individual number symbols immediately, before the final transcript',()=>{
 for(const lang of ['zh-CN','zh-TW']){const h=harness('chinese',lang,['三','八']);h.stream.update([result('38')]);assert.deepEqual(h.out,['3','8']);h.stream.update([result('38',true)]);assert.deepEqual(h.out,['3','8']);}
});
test('Digit, Hanzi and pinyin revisions keep the same queued answers after targets have been consumed',()=>{
 for(const first of ['3','三','san1','sān']){const h=harness('chinese','zh-CN',['三','八']);h.stream.update([result(first)]);assert.deepEqual(h.out,[first]);h.state.candidates=[{answer:'八',aliases:[]}];h.stream.update([result('38')]);assert.deepEqual(h.out,[first,'8']);h.state.candidates=[];h.stream.update([result('三八',true)]);h.stream.update([result('38',true)]);assert.deepEqual(h.out,[first,'8']);}
 const h=harness('chinese','zh-CN',['三','八','九']);h.stream.update([result('三八')]);h.stream.update([result('389',true)]);assert.deepEqual(h.out,['三','八','9']);
});
test('Chinese digit splitting preserves ten, full-width digits, raw punctuation and unmatched digits',()=>{
 const h=harness('chinese','zh-CN',['三','十','八']);h.stream.update([result('“３１０８！”')]);assert.deepEqual(h.out,['“３','１０','８！”']);h.stream.update([result('三十八',true)]);assert.equal(h.out.length,3);
 const context={lesson:'chinese',language:'zh-CN',candidates:[]};
 for(const [raw,expected] of [['10',['10']],['103',['10','3']],['110',['1','10']],['1010',['10','10']],['390',['3','9','0']],['三108',['三','10','8']]])assert.deepEqual(Array.from(SC.tokenizeSpeech(raw,context)),expected);
});
test('Number-run splitting is exclusive to Chinese speech tokens, without splitting pinyin or decimals',()=>{
 for(const lesson of ['math','bopomofo','letters','english','swedish'])assert.deepEqual(Array.from(SC.tokenizeSpeech('38',{lesson,language:'zh-CN',candidates:[]})),['38']);
 const context={lesson:'chinese',language:'zh-CN',candidates:[]};for(const raw of ['san3','ba1','-38','3.8','3,8','38abc'])assert.deepEqual(Array.from(SC.tokenizeSpeech(raw,context)),[raw]);
 assert(!SC.matches('38',SC.modes.chinese.items[2],'chinese','zh-CN','text'));assert(SC.matches('10',SC.modes.chinese.items[9],'chinese','zh-CN','speech'));
});
console.log(checks+' streaming speech and matching checks passed.');
