'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const context=vm.createContext({Event,EventTarget,CustomEvent,console,performance});
for(const name of ['pinyin','data','language-exercises-data','language-exercises','homework','voice','speech','input','game','studio','studio-renderer'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../resources/'+name+'.js'),'utf8'),context);
const SC=context.Starlight,events=[],g=new SC.StudioGame({random:()=>.4,onEvent:e=>events.push(e.type)});
g.start({mode:'math-addition'});assert.equal(g.paint,0);g.choose('color',2);assert.equal(g.color,14,'choosing a colour does not unlock it');
g.queue.enqueue('wrong');g.update(.1);assert.equal(g.paint,0);assert.equal(g.color,14);assert(g.canAnswer());
g.queue.enqueue(g.targets[0].item.answer);g.update(.1);assert.equal(g.color,2);assert.equal(g.paint,1);assert(!g.canAnswer());
g.consume(.7);assert(Math.abs(g.paint-.3)<1e-9);g.update(100000);assert(Math.abs(g.paint-.3)<1e-9,'paint never expires with time');
for(const tool of ['large','small','bucket']){g.choose('tool',tool);assert.equal(g.tool,tool,'tools switch immediately');assert(!g.pending);assert(!g.canAnswer());assert(Math.abs(g.paint-.3)<1e-9,'switching tools preserves remaining paint');}
g.choose('color',2);const chosen=g.targets[0];g.choose('tool','small');assert.equal(g.targets[0],chosen,'tool switching preserves a pending colour question');g.cancelQuestion();assert(!g.pending);assert(Math.abs(g.paint-.3)<1e-9);
g.choose('tool','bucket');g.choose('color',2);g.queue.enqueue(g.targets[0].item.answer);g.update(.1);
for(let i=0;i<5;i++)g.consume(.2);assert.equal(g.paint,0,'exactly five fills');
assert.equal(g.pending.type,'color');assert.equal(g.pending.value,2,'empty bucket automatically asks for the colour just used');assert(g.canAnswer());
const refill=g.targets[0],questions=events.filter(e=>e==='studio-question').length;
for(const tool of ['small','large','bucket']){g.choose('tool',tool);assert.equal(g.tool,tool);assert.equal(g.paint,0,'tool switching cannot refill empty paint');assert.equal(g.targets[0],refill);assert(g.canAnswer());}
g.consume(0);g.cancelQuestion();assert.equal(g.targets[0],refill,'empty-paint question cannot be dismissed or regenerated by consuming zero');assert.equal(events.filter(e=>e==='studio-question').length,questions);
g.queue.enqueue('wrong');g.update(.1);assert.equal(g.paint,0);assert.equal(g.targets[0],refill,'wrong answer keeps the refill problem');
g.pause();const clock=g.clock;g.update(20);assert.equal(g.clock,clock);g.resume();g.queue.enqueue(g.targets[0].item.answer);g.update(.1);assert.equal(g.paint,1,'answering the automatic question refills paint');assert.equal(g.tool,'bucket');assert.equal(g.color,2);
assert.equal(g.state,'playing');assert(!events.includes('end'));assert.equal(g.score,undefined);
for(const mode of Object.keys(SC.modes).filter(m=>m!=='homework'))for(const lang of SC.isTranslation(mode)?['sv-SE','en-US']:[SC.modes[mode].lang]){
 g.start({mode,lang});g.choose('tool','large');assert.equal(g.tool,'large',mode);assert.equal(g.targets.length,0);assert.equal(g.paint,0);g.choose('color',14);assert.equal(g.targets.length,1);g.queue.enqueue(g.targets[0].item.answer);g.update(.1);assert.equal(g.paint,1,mode);
}
g.start({mode:'homework',lang:'sv-SE',items:[{answer:'hej',label:'hej'}]});g.choose('color',4);g.queue.enqueue('hej');g.update(.1);assert.equal(g.color,4,'one-answer homework works');
g.start({mode:'chinese',lang:'zh-TW',items:[{answer:'你',label:'你',hint:'nǐ',translation:'du'}]});
for(const answer of ['du','ni','你']){g.choose('color',6);g.queue.enqueue(answer);g.update(.1);assert.equal(g.paint,1,answer);g.consume(1);}
const image={width:7,height:5,data:new Uint8ClampedArray(7*5*4).fill(255)};
for(let y=0;y<5;y++)image.data.set([0,0,0,255],(y*7+3)*4);
assert.equal(SC.studioFill(image,1,2,'#e64b4b'),15);assert.deepEqual([...image.data.slice(0,4)],[230,75,75,255]);assert.deepEqual([...image.data.slice(16,20)],[255,255,255,255]);
assert.equal(SC.studioFill(image,1,2,'#e64b4b'),0,'same-colour fill costs no paint');assert.equal(SC.studioFill(image,-1,0,'#000000'),0);
assert.equal(SC.studioFill(image,6,4,'#4088ce'),15,'region remains bounded by brush stroke');
const large={width:960,height:640,data:new Uint8ClampedArray(960*640*4).fill(255)};assert.equal(SC.studioFill(large,959,639,'#263238'),960*640,'whole-paper fill without stack overflow');
console.log('PASS studio selection, refills, exercises/aliases, no scoring and bounded fill');

// Verify actual stroke accounting across both brush sizes and event sampling rates.
function brush(tool='small'){
 const game=new SC.StudioGame();game.start();game.paint=1;game.tool=tool;
 const renderer=Object.assign(Object.create(SC.StudioRenderer.prototype),{game,paper:{width:960},strokeLength:0,chargedDistance:0,ctx:{beginPath(){},arc(){},fill(){},moveTo(){},lineTo(x,y){this.last=[x,y];},stroke(){}},endStroke(){this.stopped=true;}});
 renderer.segment({x:0,y:0},{x:0,y:0});return renderer;
}
for(const tool of ['small','large']){
 for(const steps of [1,20,600]){const r=brush(tool);assert(Math.abs(r.game.paint-(1-30/2880))<1e-9,'a dot costs 30 pixels');for(let i=1;i<=steps;i++)r.segment({x:(i-1)*600/steps,y:100},{x:i*600/steps,y:100});assert(Math.abs(r.game.paint-(1-600/2880))<1e-9,'600 pixels cost the same at every event rate');}
 const r=brush(tool);r.segment({x:0,y:0},{x:960,y:0});r.segment({x:960,y:0},{x:0,y:0});r.segment({x:0,y:0},{x:960,y:0});assert.equal(r.game.paint,0);assert(r.stopped,'three canvas widths exhaust the refill');
 assert.equal(r.game.pending.type,'color');assert.equal(r.game.pending.value,r.game.color,'brush exhaustion requests the current colour');assert(r.game.canAnswer());
 const partial=brush(tool);partial.segment({x:0,y:0},{x:2800,y:0});partial.segment({x:2800,y:0},{x:3000,y:0});assert.equal(partial.game.paint,0);assert(Math.abs(partial.ctx.last[0]-2880)<1e-6,'the last segment ends exactly when paint is exhausted');
 const dot=brush(tool);dot.game.paint=30/2880;dot.strokeLength=0;dot.chargedDistance=0;dot.segment({x:0,y:0},{x:0,y:0});assert(dot.stopped&&dot.game.canAnswer(),'a final dot releases the pointer and opens a refill question immediately');
}
console.log('PASS distance-based paint: 30-pixel dots, event-independent strokes, three-width refill');

function solveRefill(game){game.choose('color',game.color);game.queue.enqueue(game.targets[0].item.answer);game.update(.01);}
for(const tool of ['small','large']){
 const r=brush(tool),game=r.game;assert(!game.brushIsFree(),'no free period before a correct answer');solveRefill(game);
 assert(game.brushIsFree());assert.equal(game.brushFreeUntil-game.clock,15);
 r.segment({x:0,y:0},{x:6000,y:0});assert.equal(game.paint,1);assert.equal(r.ctx.last[0],6000,'free strokes are not clipped to the distance budget');
 game.update(14.99);r.segment({x:6000,y:0},{x:6000,y:0});assert.equal(game.paint,1,'dots are free too');
 const until=game.brushFreeUntil;game.pause();game.update(100);game.resume();assert(game.brushIsFree(),'pause preserves the free period');
 game.choose('tool','bucket');assert(!game.brushIsFree());game.choose('tool',tool);assert.equal(game.brushFreeUntil,until,'switching tools does not extend the period');
 game.update(until-game.clock);assert(!game.brushIsFree(),'distance charging starts at exactly 15 seconds');
 r.segment({x:6000,y:0},{x:6100,y:0});assert(Math.abs(game.paint-(1-100/2880))<1e-9,'a continuous stroke only charges its post-grace distance');
 solveRefill(game);game.update(15);r.strokeLength=0;r.chargedDistance=0;r.segment({x:0,y:0},{x:0,y:0});assert(Math.abs(game.paint-(1-30/2880))<1e-9,'a dot after the free period costs 30 pixels');
 game.choose('color',2);game.queue.enqueue('wrong');game.update(.1);assert(!game.brushIsFree(),'wrong answers do not grant free painting');
 game.queue.enqueue(game.targets[0].item.answer);game.update(.1);assert(game.brushIsFree(),'every correct answer starts a fresh free period');
 game.start();assert(!game.brushIsFree(),'a new game resets the free period');
}
const freeAfterBucket=brush(),bucketGame=freeAfterBucket.game;solveRefill(bucketGame);bucketGame.choose('tool','bucket');
for(let i=0;i<5;i++)bucketGame.consume(.2);assert.equal(bucketGame.paint,0,'bucket still uses five fills during the free-brush period');assert(!bucketGame.canPaint());
bucketGame.choose('tool','small');assert(bucketGame.canPaint(),'brushes remain free even if the bucket emptied the paint');bucketGame.cancelQuestion();
freeAfterBucket.segment({x:0,y:0},{x:6000,y:0});assert.equal(bucketGame.paint,0);assert.equal(freeAfterBucket.ctx.last[0],6000);assert(!bucketGame.pending);
bucketGame.update(15);assert(!bucketGame.canPaint());assert.equal(bucketGame.pending.value,bucketGame.color,'expiry automatically asks for a refill if the bucket used all paint');
console.log('PASS 15-second free brushes: timing, pause, tool switching, continuous strokes, correct answers and bucket exclusion');

// Synthetic antialias ramps around a one-pixel outline: recolour only the
// background component on the clicked side, without shrinking/crossing the ink.
const rgb=hex=>hex.slice(1).match(/../g).map(c=>parseInt(c,16));
const mix=(background,ink,a)=>background.map((c,i)=>Math.round(c*(1-a)+ink[i]*a));
function edgePicture(background,ink){
 const image={width:9,height:5,data:new Uint8ClampedArray(9*5*4)};
 for(let y=0;y<5;y++)for(let x=0;x<9;x++)image.data.set([...mix(background,ink,[0,0,.25,.75,1,.75,.25,0,0][x]),255],(y*9+x)*4);
 return image;
}
function closePixel(image,x,expected,tolerance=3){const actual=[...image.data.slice((2*9+x)*4,(2*9+x)*4+3)];assert(actual.every((v,i)=>Math.abs(v-expected[i])<=tolerance),`${actual} != ${expected}`);}
for(const [,hex] of SC.studioColors){
 if(hex==='#ffffff')continue;
 const ink=rgb(hex),ramp=edgePicture([255,255,255],ink),original=ramp.data.slice();
 SC.studioFill(ramp,0,2,hex);
 for(const x of [0,1,2,3,4])closePixel(ramp,x,ink);
 for(let y=0;y<5;y++)assert.deepEqual(ramp.data.slice((y*9+4)*4,(y*9+9)*4),original.slice((y*9+4)*4,(y*9+9)*4),'solid outline and opposite side stay unchanged');
}
for(const [background,ink] of [[[255,255,255],rgb('#263238')],[rgb('#263238'),[255,255,255]]]){
 const ramp=edgePicture(background,ink);
 for(const fill of ['#4088ce','#f4cf45','#e64b4b']){
  SC.studioFill(ramp,0,2,fill);
  closePixel(ramp,2,mix(rgb(fill),ink,.25));closePixel(ramp,3,mix(rgb(fill),ink,.75));closePixel(ramp,4,ink,0);closePixel(ramp,7,background,0);
 }
}
console.log('PASS antialiased fill: every outline colour, thin boundaries, light-on-dark and repeated recolouring');

const coincidentalGrey=edgePicture([255,255,255],rgb('#263238'));
coincidentalGrey.data.set([141,148,151,255],(2*9+2)*4);
SC.studioFill(coincidentalGrey,0,2,'#263238');closePixel(coincidentalGrey,2,rgb('#263238'));
console.log('PASS edge blends that coincide with a different palette colour');
