/* Two main words plus independent accepted alternatives for each direction.
   Alternative answers are never automatically promoted to prompts. */
(function(root){
'use strict';const SC=root.Starlight;
// [main A, main B, alternatives accepted for A, alternatives accepted for B].
SC.wordPairs={
  'swedish-opposites':[
    ["stor","liten",["väldig","enorm"],["pytteliten"]],
    ["lång","kort",[],[]],
    ["hög","låg",[],[]],
    ["bred","smal",["vid"],["trång"]],
    ["tjock","tunn",[],[]],
    ["tung","lätt",["svår","krånglig","besvärlig"],[]],
    ["varm","kall",["het"],["sval","kylig"]],
    ["ljus","mörk",[],["mörker"]],
    ["snabb","långsam",["kvick","rask"],["seg","trög"]],
    ["tidig","sen",[],[]],
    ["ung","gammal",[],["äldre"]],
    ["ny","gammal",["oanvänd"],["begagnad","använd"]],
    ["ren","smutsig",[],["lortig","skitig"]],
    ["torr","våt",[],["blöt","fuktig"]],
    ["fylld","tom",["full"],["tömd"]],
    ["öppen","stängd",[],["sluten","igen"]],
    ["stark","svag",["kraftig"],["klen"]],
    ["hård","mjuk",[],["mild","snäll"]],
    ["slät","skrovlig",["jämn"],["ojämn","grov","sträv","rynkig","gropig","knottrig"]],
    ["vass","trubbig",["spetsig"],["slö"]],
    ["rak","krokig",[],["böjd","kurvig"]],
    ["rund","kantig",[],["fyrkantig"]],
    ["hel","trasig",["fungerande"],["sönder","söndrig","defekt","halv","delad","halverad"]],
    ["frisk","sjuk",["kry"],["krasslig"]],
    ["vaken","sovande",[],["sover","trött","sömnig"]],
    ["levande","död",["vid liv"],["livlös"]],
    ["glad","ledsen",["lycklig","munter"],["sorgsen","olycklig","nedstämd"]],
    ["modig","feg",["orädd","djärv","tapper"],["rädd","skraj","ängslig"]],
    ["snäll","elak",["vänlig","god"],["taskig","ovänlig","dum","hård"]],
    ["artig","oartig",["hövlig"],["ohövlig","oförskämd"]],
    ["ärlig","oärlig",["sanningsenlig","sannfärdig"],["lögnaktig","falsk"]],
    ["flitig","lat",["arbetsam","idog"],["slö","overksam"]],
    ["rik","fattig",["förmögen"],["medellös","mager"]],
    ["generös","snål",["givmild"],["ogin"]],
    ["enkel","svår",["lätt","okomplicerad"],["krånglig","komplicerad","besvärlig"]],
    ["billig","dyr",[],["kostsam"]],
    ["nära","långt borta",["intill"],["långt bort","långt ifrån","avlägset","fjärran"]],
    ["inne","ute",["inomhus"],["utomhus"]],
    ["uppe","nere",["ovan","upp"],["nedanför","ner"]],
    ["framför","bakom",[],[]],
    ["över","under",["ovanför"],["nedanför"]],
    ["först","sist",[],["sist av alla"]],
    ["början","slut",["start","inledning"],["avslut","avslutning"]],
    ["dag","natt",[],[]],
    ["allt","ingenting",["allting"],["inget"]],
    ["alltid","aldrig",["ständigt"],[]],
    ["många","få",[],[]],
    ["mer","mindre",["mera"],[]],
    ["vinna","förlora",["segra"],[]],
    ["öka","minska",["höja"],["sänka"]]
  ],
  'swedish-synonyms':[
    ["glad","lycklig",["munter","lycklig","upprymd","gladlynt"],["glad","munter","upprymd"]],
    ["ledsen","sorgsen",["sorgsen","olycklig","nedstämd","bedrövad"],["ledsen","olycklig","nedstämd","bedrövad"]],
    ["arg","ilsken",["ilsken","förargad","vred","rasande","irriterad"],["arg","vred","rasande","irriterad"]],
    ["rädd","skraj",["skraj","ängslig","skrämd","förskräckt"],["rädd","ängslig","skrämd","förskräckt"]],
    ["snäll","vänlig",["vänlig","god","godhjärtad","trevlig","hjälpsam"],["snäll","god","godhjärtad","trevlig","hjälpsam"]],
    ["elak","taskig",["taskig","ovänlig","dum","illvillig","otrevlig"],["elak","ovänlig","dum","illvillig","otrevlig"]],
    ["modig","orädd",["orädd","djärv","tapper"],["modig","djärv","tapper"]],
    ["trött","sömnig",["sömnig","dåsig","slö"],["trött","dåsig","slö","utmattad","utsliten","slut"]],
    ["energisk","livlig",["alert","vaken","livlig","pigg","aktiv","livfull","intensiv"],["pigg","vaken","energisk","alert","aktiv","livfull"]],
    ["rolig","skojig",["skojig","kul","lustig","underhållande"],["rolig","kul","lustig","underhållande"]],
    ["konstig","märklig",["märklig","underlig","besynnerlig","egendomlig","udda"],["konstig","underlig","besynnerlig","egendomlig","udda"]],
    ["vacker","snygg",["fin","snygg","skön","fager","tjusig","prydlig","stilig"],["vacker","skön","fager","tjusig","fin"]],
    ["enorm","jättelik",["jättelik","väldig","gigantisk","stor","jättestor"],["enorm","väldig","gigantisk","stor","jättestor"]],
    ["minimal","pytteliten",["ytterst liten","mycket liten","mikroskopisk"],["ytterst liten","mycket liten","mikroskopisk"]],
    ["snabb","kvick",["kvick","rask","blixtsnabb","hastig"],["snabb","rask","hastig"]],
    ["långsam","trög",["trög","seg","saktfärdig","sakta"],["långsam","seg","saktfärdig","sakta"]],
    ["enkel","okomplicerad",["lätt","okomplicerad","simpel"],["enkel","simpel","lätt"]],
    ["svår","krånglig",["krånglig","knepig","komplicerad","besvärlig","invecklad"],["svår","knepig","komplicerad","besvärlig","invecklad"]],
    ["klipsk","intelligent",["intelligent","klok","begåvad","listig","smart"],["smart","klok","begåvad","klipsk"]],
    ["nyfiken","vetgirig",["vetgirig","frågvis","kunskapstörstig"],["nyfiken","frågvis","kunskapstörstig"]],
    ["viktig","betydelsefull",["betydelsefull","väsentlig","central","angelägen"],["viktig","väsentlig","central","angelägen"]],
    ["säker","trygg",["trygg","ofarlig","riskfri"],["säker","ofarlig","riskfri","viss","övertygad","bestämd"]],
    ["tyst","ljudlös",["ljudlös","stilla","knäpptyst"],["tyst","stilla"]],
    ["lugn","stillsam",["stillsam","fridfull","rofylld","stilla"],["lugn","fridfull","rofylld","stilla"]],
    ["stark","kraftig",["kraftig","kraftfull","muskulös","rejäl","grov","tjock"],["stark","kraftfull","muskulös","intensiv","het"]],
    ["svag","klen",["klen","kraftlös","orkeslös"],["svag","kraftlös","orkeslös","tunn","blaskig"]],
    ["börja","starta",["starta","inleda","påbörja","sätta igång"],["börja","inleda","sätta igång"]],
    ["sluta","upphöra",["upphöra","avsluta","lägga av"],["sluta","lägga av","stänga","upphöra med"]],
    ["prata","tala",["tala","snacka","konversera"],["prata","samtala","snacka","konversera"]],
    ["titta","kika",["kika","se","blicka","kolla"],["titta","se","blicka","kolla"]],
    ["skrika","ropa",["ropa","gapa","ryta","hojta"],["skrika","gapa","hojta"]],
    ["gråta","snyfta",["lipa","böla","snyfta"],["gråta","böla","lipa"]],
    ["springa","kuta",["kuta","löpa","rusa","lubba"],["springa","löpa","rusa","lubba"]],
    ["gå","promenera",["promenera","vandra","strosa","spatsera"],["gå","vandra","strosa","spatsera"]],
    ["hoppa","skutta",["skutta"],["hoppa"]],
    ["kasta","slänga",["slänga","slunga","hiva","kasta bort"],["kasta","slunga","hiva","slänga bort"]],
    ["få","erhålla",["erhålla","motta","ta emot"],["få","motta","ta emot","några","enstaka","inte många"]],
    ["ge","skänka",["skänka","ge bort","donera","lämna","överlämna"],["ge","donera","lämna","överlämna"]],
    ["köpa","inhandla",["inhandla","införskaffa"],["köpa","införskaffa","handla"]],
    ["arbeta","jobba",["jobba","knega"],["arbeta","knega"]],
    ["hjälpa","assistera",["assistera","bistå","stötta","understödja"],["hjälpa","bistå","stötta","understödja"]],
    ["förstå","begripa",["begripa","fatta","inse"],["förstå","fatta","inse"]],
    ["tycka om","gilla",["gilla","uppskatta"],["tycka om","uppskatta"]],
    ["vän","kompis",["kompis","kamrat","polare"],["vän","kamrat","polare","bekant"]],
    ["barn","unge",["unge","ungdom","småtting"],["barn","ungdom","småtting"]],
    ["flicka","tjej",["tjej","jänta","tös","flickvän","kvinna"],["flicka","jänta","tös"]],
    ["pojke","kille",["kille","gosse","grabb","man","pojkvän"],["pojke","gosse","grabb"]],
    ["mamma","mor",["mor","moder"],["mamma","moder","morsa"]],
    ["pappa","fader",["far","fader","farsa"],["pappa","farsa","far"]],
    ["present","gåva",["gåva","skänk"],["present","skänk"]]
  ],
  'english-opposites':[
    ["big","small",["large","huge"],["little","tiny"]],
    ["long","short",[],[]],
    ["tall","short",["high"],["low"]],
    ["wide","narrow",["broad"],["slim"]],
    ["thick","thin",[],[]],
    ["heavy","light",["dark","dim"],["lightweight"]],
    ["hot","cold",["warm"],["cool","chilly"]],
    ["light","dark",["bright"],["dim","heavy"]],
    ["fast","slow",["quick","speedy"],["sluggish"]],
    ["early","late",[],[]],
    ["young","old",[],["elderly"]],
    ["new","old",["unused"],["used","second-hand","secondhand"]],
    ["clean","dirty",[],["filthy","unclean"]],
    ["dry","wet",[],["damp","soaked"]],
    ["filled","empty",["full"],[]],
    ["open","closed",[],["shut","secretive"]],
    ["strong","weak",["powerful"],["feeble","mild","faint"]],
    ["hard","soft",["firm"],["gentle","kind","easy"]],
    ["smooth","rough",["even"],["uneven","bumpy"]],
    ["sharp","blunt",["pointed"],["dull"]],
    ["straight","crooked",[],["bent","curved","curly"]],
    ["round","square",[],["angular"]],
    ["whole","broken",["intact","unbroken","working"],["damaged","half","partial"]],
    ["healthy","ill",["well","fit"],["sick","unwell"]],
    ["awake","asleep",[],["sleeping","sleepy"]],
    ["alive","dead",["living"],["lifeless"]],
    ["happy","sad",["glad","cheerful"],["unhappy","miserable"]],
    ["brave","cowardly",["courageous","fearless"],["afraid","scared","fearful"]],
    ["kind","unkind",["nice","friendly"],["nasty","cruel","unfriendly","mean","hard"]],
    ["polite","rude",["courteous"],["impolite","discourteous"]],
    ["honest","dishonest",["truthful"],["untruthful"]],
    ["hard-working","lazy",["hardworking","diligent","industrious"],["idle","inactive"]],
    ["rich","poor",["wealthy"],["penniless"]],
    ["generous","selfish",["giving"],["stingy","mean","ungenerous"]],
    ["easy","difficult",["simple"],["hard","tricky","complicated"]],
    ["cheap","expensive",["inexpensive"],["costly","dear"]],
    ["near","far",["close","nearby"],["far away","distant"]],
    ["inside","outside",["indoors"],["outdoors"]],
    ["up","down",["above"],["below"]],
    ["in front of","behind",["ahead of","before"],["at the back of"]],
    ["above","below",["over","up"],["under","underneath","beneath","down"]],
    ["first","last",["initial"],["final"]],
    ["beginning","end",["start"],["ending","finish"]],
    ["day","night",[],[]],
    ["everything","nothing",["all"],[]],
    ["always","never",[],[]],
    ["many","few",["lots of","a lot of"],["not many","little"]],
    ["more","less",[],["fewer"]],
    ["win","lose",["succeed"],["be defeated"]],
    ["increase","decrease",["raise","grow"],["reduce","lower","shrink"]]
  ],
  'english-synonyms':[
    ["happy","glad",["glad","cheerful","joyful","pleased","delighted"],["happy","cheerful","joyful","pleased","delighted"]],
    ["sad","unhappy",["unhappy","miserable","sorrowful","upset","down","blue","depressed","downcast","low"],["sad","miserable","sorrowful","upset","down","blue","depressed","downcast","low"]],
    ["angry","furious",["mad","furious","cross","annoyed"],["angry","cross","annoyed","mad"]],
    ["afraid","scared",["scared","frightened","fearful","terrified"],["afraid","frightened","fearful","terrified"]],
    ["welcoming","friendly",["friendly","nice","caring","helpful","gentle","kind"],["kind","nice","caring","welcoming","pleasant"]],
    ["cruel","unkind",["unkind","nasty","unfriendly","horrible","mean"],["mean","nasty","cruel","unfriendly","horrible"]],
    ["brave","courageous",["courageous","fearless","bold","heroic"],["brave","fearless","bold","heroic"]],
    ["tired","sleepy",["sleepy","drowsy","weary"],["tired","drowsy","weary","exhausted","worn out","fatigued","bored","fed up"]],
    ["clever","intelligent",["smart","intelligent","bright","brainy"],["clever","bright","brainy","smart"]],
    ["funny","amusing",["amusing","humorous","hilarious","comical","entertaining"],["funny","humorous","hilarious","comical","entertaining","strange","odd","weird","unusual"]],
    ["strange","unusual",["odd","unusual","weird","peculiar","curious","funny"],["strange","weird","peculiar","curious","odd","funny"]],
    ["beautiful","lovely",["pretty","lovely","attractive","gorgeous","good-looking"],["beautiful","attractive","gorgeous","good-looking","pretty"]],
    ["big","large",["large","huge","enormous","giant","gigantic","massive","vast"],["big","huge","enormous","giant","gigantic","massive","vast","important","major","grown-up","grown up"]],
    ["small","tiny",["little","tiny","miniature","mini"],["small","miniature","mini","little"]],
    ["huge","enormous",["enormous","massive","gigantic","immense","giant","big","large"],["huge","massive","gigantic","immense","giant","big","large"]],
    ["swift","quick",["quick","rapid","speedy","fast"],["fast","rapid","speedy","swift"]],
    ["slow","sluggish",["sluggish","unhurried","leisurely"],["slow","unhurried","leisurely","slow down","decelerate","boring"]],
    ["easy","simple",["simple","straightforward","effortless"],["easy","straightforward","uncomplicated"]],
    ["tricky","difficult",["difficult","challenging","tough","hard"],["hard","tricky","challenging","tough"]],
    ["important","significant",["significant","major","essential","vital"],["important","major","meaningful","big"]],
    ["safe","protected",["secure","protected","sheltered"],["safe","sheltered","secure","strongbox","lockbox"]],
    ["quiet","silent",["silent","noiseless","soundless"],["quiet","noiseless","soundless","calm","peaceful","hushed","soft"]],
    ["calm","peaceful",["peaceful","quiet","tranquil","relaxed"],["calm","quiet","tranquil","relaxed"]],
    ["strong","powerful",["powerful","mighty","muscular"],["strong","mighty","muscular","intense","concentrated","heavy"]],
    ["weak","feeble",["feeble","frail","powerless"],["weak","frail","powerless","watery","dilute","diluted","thin","faint"]],
    ["begin","start",["start","commence","beginning","origin","onset"],["begin","commence"]],
    ["finish","end",["end","complete","conclude","ending","conclusion","termination"],["finish","complete","conclude","completion","ending","coating"]],
    ["speak","talk",["talk","chat","converse","conversation","discussion","speech"],["speak","chat","converse"]],
    ["look","peek",["peek","glance","peep"],["look","glance","peep"]],
    ["shout","yell",["yell","scream","call","holler","cry"],["shout","scream","call","holler","cry","a cry"]],
    ["cry","weep",["weep","sob","bawl"],["cry","sob","bawl","shout","call","yell"]],
    ["laugh","chuckle",["chuckle","giggle","chortle"],["laugh","giggle","chortle"]],
    ["run","sprint",["sprint","dash","race","rush"],["run","dash","race","rush","jog","operate","function","manage"]],
    ["jump","leap",["leap","hop","bound"],["jump","hop","bound"]],
    ["throw","toss",["toss","hurl","chuck","fling"],["throw","hurl","chuck","fling","cast"]],
    ["give","donate",["donate","offer","gift","give away"],["give","offer","gift","give away"]],
    ["buy","purchase",["purchase"],["buy"]],
    ["work","labour",["labour","labor","toil"],["labor","work","toil","job","task","function","operate"]],
    ["help","assist",["assist","aid","support"],["help","aid","support","assistance"]],
    ["answer","reply",["reply","respond","response"],["answer","respond","response","solution"]],
    ["understand","comprehend",["comprehend","grasp","follow","get"],["understand","grasp","follow","get"]],
    ["like","enjoy",["enjoy","love","be fond of"],["like","love","be fond of","similar to","such as"]],
    ["friend","pal",["pal","buddy","mate","companion"],["friend","buddy","mate","companion"]],
    ["child","kid",["kid","youngster"],["child","youngster"]],
    ["mother","mum",["mum","mom","mummy","mommy","mama"],["mom","mother","mummy","mommy","mama"]],
    ["father","dad",["dad","daddy","papa"],["father","daddy","papa"]],
    ["present","gift",["gift","give","donate"],["present","current","here","now","existing","introduce","show"]],
    ["home","house",["house","dwelling","residence","building","accommodate"],["home","dwelling","residence","at home"]],
    ["ill","unwell",["sick","unwell","poorly"],["ill","poorly","sick"]],
    ["near","nearby",["close","nearby","adjacent"],["near","adjacent","close"]]
  ],
  'translation-sv-en-1':[
    ["katt","cat",["kisse","misse","kissemiss"],[]],
    ["hund","dog",["vovve"],[]],
    ["häst","horse",[],[]],
    ["ko","cow",["kossa"],[]],
    ["gris","pig",["svin"],[]],
    ["får","sheep",[],["get","gets","receive","receives","may","can","is allowed to"]],
    ["fågel","bird",[],[]],
    ["fisk","fish",["fiska"],[]],
    ["mus","mouse",[],[]],
    ["kanin","rabbit",[],["bunny"]],
    ["äpple","apple",[],[]],
    ["päron","pear",[],[]],
    ["banan","banana",[],[]],
    ["apelsin","orange",["orange"],[]],
    ["bröd","bread",[],[]],
    ["mjölk","milk",["mjölka"],[]],
    ["vatten","water",["vattna"],[]],
    ["ost","cheese",[],[]],
    ["ägg","egg",[],[]],
    ["potatis","potato",[],["potatoes"]],
    ["morot","carrot",[],[]],
    ["glass","ice cream",[],["ice-cream","icecream"]],
    ["hus","house",["hem","bostad","hysa","inhysa"],["home"]],
    ["skola","school",["stim","undervisa"],[]],
    ["bord","table",["tabell"],[]],
    ["stol","chair",["säte","ordförande"],[]],
    ["dörr","door",["port"],[]],
    ["fönster","window",[],[]],
    ["säng","bed",["bädd","rabatt"],[]],
    ["bok","book",["boka"],["beech"]],
    ["penna","pencil",["blyertspenna"],["pen","quill"]],
    ["ryggsäck","backpack",[],["rucksack","schoolbag","school bag"]],
    ["sko","shoe",[],[]],
    ["strumpa","sock",["socka"],[]],
    ["hatt","hat",["mössa","keps","huvudbonad"],[]],
    ["byxor","trousers",["långbyxor"],["pants"]],
    ["hand","hand",["visare"],[]],
    ["fot","foot",[],["base"]],
    ["huvud","head",["skalle","chef","ledare","rektor"],[]],
    ["öga","eye",["ögla","nålsöga"],[]],
    ["öra","ear",["ax"],[]],
    ["näsa","nose",["nos","snok"],[]],
    ["mun","mouth",["mynning"],[]],
    ["tand","tooth",[],[]],
    ["sol","sun",["sola"],[]],
    ["måne","moon",[],[]],
    ["stjärna","star",[],[]],
    ["regn","rain",["regna"],[]],
    ["snö","snow",["snöa"],[]],
    ["träd","tree",[],[]]
  ],
  'translation-sv-en-2':[
    ["äta","eat",["äter","ät","käka","käkar"],[]],
    ["dricka","drink",["dryck","dricker","drick"],[]],
    ["sova","sleep",["sömn","sover","sov"],[]],
    ["vakna","wake up",["vakna upp"],["wake","awake"]],
    ["tvätta","wash",["tvätta sig","tvätt","tvättar"],["clean"]],
    ["läsa","read",["läste","läst","läser","läs"],[]],
    ["skriva","write",["skriver","skriv"],[]],
    ["rita","draw",["teckna","dra","drar","drag","oavgjort","ritar","tecknar"],["sketch","design"]],
    ["sjunga","sing",["sjunger","sjung"],[]],
    ["dansa","dance",["dansar"],[]],
    ["spela","play",["pjäs","lek","leker","leker med","spelar","spela teater"],["act","perform","gamble"]],
    ["öva","practise",["träna","öva sig","övar","tränar"],["practice","train","rehearse"]],
    ["springa","run",["löpa","kuta","springer","spring","köra","kör","driva","fungerar","fungera"],[]],
    ["gå","walk",["promenera","vandra","promenad","går"],["go","leave","work","function"]],
    ["hoppa","jump",["skutta","hopp","hoppar"],["leap","hop"]],
    ["simma","swim",["simmar"],[]],
    ["flyga","fly",["fluga","flyger"],[]],
    ["öppna","open",["öppnar","öppen","öppet"],[]],
    ["stänga","close",["sluta","nära","stäng","stänger","avsluta","avslutar","slut"],["shut"]],
    ["köpa","buy",["handla","inhandla","köper","köp"],["purchase"]],
    ["sälja","sell",["säljer","sälj"],[]],
    ["ge","give",["giva","skänka","ger"],["offer","provide","grant","hand"]],
    ["hitta","find",["finna","fynd","hittar","finner","finn"],["discover","locate"]],
    ["leta efter","look for",["söka","söka efter","leta"],["search for","seek"]],
    ["fråga","ask",["ställa en fråga","frågar","be","ber"],["question","inquire","enquire","query"]],
    ["svara","answer",["besvara","ge svar","svar","svarar"],["reply","respond"]],
    ["hjälpa","help",["assistera","bistå","hjälp","hjälper"],["assist","aid"]],
    ["lära sig","learn",["lära","lär","lär sig"],[]],
    ["förstå","understand",["begripa","fatta","förstår"],["comprehend"]],
    ["vänta","wait",["invänta","väntan","väntar"],[]],
    ["stor","big",["väldig","stort","stora","viktig","viktigt"],["large"]],
    ["liten","small",["småväxt","litet","små","lilla"],["little"]],
    ["lång","long",["långt","långa","längta"],["tall"]],
    ["kort","short",["korta","kortvarig"],["card","photo","photograph"]],
    ["varm","warm",["het","varmt","varma","hett","heta","värma"],["hot"]],
    ["kall","cold",["kylig","kallt","kalla","förkylning"],["chilly","calling","vocation"]],
    ["glad","happy",["lycklig","munter","glatt","glada","lyckligt","lyckliga"],["glad","cheerful"]],
    ["ledsen","sad",["sorgsen","olycklig","ledset","ledsna","sorgset","sorgsna"],["unhappy"]],
    ["trött","tired",["sömnig","trötta","utmattad","utmattat","utmattade"],["sleepy"]],
    ["hungrig","hungry",["hungrigt","hungriga"],[]],
    ["törstig","thirsty",["törstigt","törstiga"],[]],
    ["snäll","friendly",["vänlig","godhjärtad","snällt","snälla","vänligt","vänliga","trevlig","trevligt","trevliga"],["nice","kind","good","gentle"]],
    ["snabb","fast",["kvick","rask","snabbt","snabba","fasta","fast","orörlig"],["quick","speedy"]],
    ["långsam","slow",["trög","seg","långsamt","långsamma","sakta","sakta ner","sakta ned"],[]],
    ["enkel","easy",["lätt","okomplicerad","enkelt","enkla","lätta"],["simple","single","plain","uncomplicated"]],
    ["svår","difficult",["krånglig","besvärlig","svårt","svåra"],["hard","tricky"]],
    ["öppen","open",["öppna","öppnar","öppet"],[]],
    ["stängd","closed",["sluten","stängt","stängda"],["shut"]],
    ["ren","clean",["rent","rena","städa","rengöra","tvätta"],["pure","reindeer"]],
    ["våt","wet",["blöt","fuktig","vått","våta","blött","blöta","blöta ner"],["damp"]]
  ],
  'translation-sv-en-3':[
    ["bibliotek","library",[],[]],
    ["lärare","teacher",["lärarinna","undervisare"],[]],
    ["elev","student",["student","skolelev","studerande"],["pupil"]],
    ["klassrum","classroom",["skolsal"],[]],
    ["läxa","homework",["läxor","hemuppgift","hemläxa"],["assignment","lesson"]],
    ["lektion","lesson",["läxa","lärdom","undervisning"],["class"]],
    ["fråga","question",["ifrågasätta"],["ask","query"]],
    ["svar","answer",["svara","besvara"],["reply","response"]],
    ["berättelse","story",["saga","historia","våning","våningsplan"],[]],
    ["språk","language",[],["tongue","speech"]],
    ["mening","sentence",["dom","straff","döma"],["meaning","purpose","opinion","intention","sense","view"]],
    ["ord","word",[],[]],
    ["bokstav","letter",["brev"],["character"]],
    ["siffra","digit",["finger","tå"],["number","figure"]],
    ["tal","number",["nummer","antal","siffra","numrera"],["speech","talk","address"]],
    ["karta","map",["kartlägga"],[]],
    ["land","country",["rike","nation","landsbygd","landet"],["nation","land","shore"]],
    ["stad","city",["ort","storstad"],["town"]],
    ["by","village",["samhälle"],["gust"]],
    ["resa","trip",["färd","utflykt","snubbla","tripp"],["journey","travel","raise","rise","erect"]],
    ["väder","weather",["vittra"],[]],
    ["årstid","season",["säsong","krydda"],[]],
    ["skog","forest",[],["wood","woods"]],
    ["hav","sea",["sjö"],["ocean"]],
    ["flod","river",["älv","å"],[]],
    ["sjö","lake",["insjö"],["sea"]],
    ["bro","bridge",["bridge","överbrygga"],[]],
    ["ö","island",[],[]],
    ["strand","beach",["sandstrand","strandsätta"],["shore"]],
    ["berg","mountain",["fjäll"],[]],
    ["minnas","remember",["komma ihåg","erinra sig","minns","kom ihåg","kommer ihåg"],["recall"]],
    ["glömma","forget",["glömma bort","glöm","glömmer"],[]],
    ["förklara","explain",["förtydliga","förklarar"],["declare"]],
    ["välja","choose",["välja ut","plocka ut","välj","väljer"],["pick","select"]],
    ["försöka","try",["pröva","prova","försök","försöker"],["attempt"]],
    ["behöva","need",["vara i behov av","behov","behöver"],["require"]],
    ["bestämma sig","decide",["bestämma","besluta","avgöra","bestäm","bestämmer","bestämmer sig"],[]],
    ["jämföra","compare",["jämför"],[]],
    ["låna","borrow",["låna av","låna in","lånar"],["lend","loan"]],
    ["låna ut","lend",["utlåna","låna","lånar ut","lånar"],["loan"]],
    ["dela","share",["dela med sig","dela på","andel","aktie","del","delar"],["divide","split","part"]],
    ["bygga","build",["konstruera","bygg","bygger","kroppsbyggnad","bygge"],["construct"]],
    ["reparera","repair",["laga","fixa","reparation","lagning","reparerar","lagar"],["fix","mend"]],
    ["undersöka","examine",["granska","inspektera","undersök","undersöker","granskar"],["investigate","inspect","explore"]],
    ["upptäcka","discover",["finna","hitta","upptäck","upptäcker"],["find","find out"]],
    ["skydda","protect",["försvara","vakta","skyddar"],["defend","guard"]],
    ["lova","promise",["utlova","löfte","lovar"],["pledge"]],
    ["tro","believe",["anse","tänka","tycka","tror"],["think","faith","belief"]],
    ["förlåta","forgive",["ursäkta","benåda","förlåt","förlåter"],["pardon","excuse"]],
    ["lyckas","succeed",["klara","klara av","efterträda","ta över","klarar","klarar av"],["manage"]]
  ]
};
SC.pairAnswerKey=(value,lang)=>SC.speechNormalize(value).replace(/[‐‑–]/g,'-').replace(lang==='sv-SE'?/^(?:att|en|ett)\s+/:/^(?:to|a|an)\s+/,'');
const specs=[
  ['swedish-opposites','Svenska ord - motsatser','sv-SE','Skriv ett ord med motsatt betydelse.'],
  ['swedish-synonyms','Svenska ord - synonymer','sv-SE','Skriv ett annat ord med samma betydelse.'],
  ['english-opposites','English words - opposites','en-US','Write a word with the opposite meaning.'],
  ['english-synonyms','English words - synonyms','en-US','Write another word with the same meaning.'],
  ['translation-sv-en-1','Översättning svenska-engelska 1','en-US','Översätt vanliga ord för djur, mat och saker.'],
  ['translation-sv-en-2','Översättning svenska-engelska 2','en-US','Översätt vardagliga verb och beskrivande ord.'],
  ['translation-sv-en-3','Översättning svenska-engelska 3','en-US','Översätt ord om skolan, omvärlden och handlingar.']
];
for(const [id,name,lang,instruction] of specs){
  const translation=id.startsWith('translation-'),languages=translation?['sv-SE','en-US']:[lang,lang];
  const prompts=new Map();
  SC.wordPairs[id].forEach(([left,right,alternativesLeft,alternativesRight],index)=>{
    const sides=[[left,...alternativesLeft],[right,...alternativesRight]];
    sides.forEach((words,direction)=>{
      const label=words[0],answerLang=languages[1-direction],key=answerLang+':'+SC.normalize(label),pairId=id+':'+index;
      const answers=sides[1-direction].filter(a=>translation||SC.pairAnswerKey(a,answerLang)!==SC.pairAnswerKey(label,answerLang));
      const item=prompts.get(key)||{id:id+':'+index+':'+direction,pairId,pairIds:[],label,answer:answers[0],aliases:[],speak:answers[0],hint:answers[0],answerLang};
      // An identical visible word must accept all its direct answers. Never
      // distinguish identical prompts using a hidden pair or hidden word sense.
      item.pairIds.push(pairId);item.aliases=[...new Set([...item.aliases,...answers])].filter(a=>a!==item.answer);
      item.answerKeys=[item.answer,...item.aliases].map(a=>SC.pairAnswerKey(a,answerLang));prompts.set(key,item);
    });
  });
  const items=[...prompts.values()];
  SC.modes[id]={name,lang,items,type:'word-pairs',translation,description:instruction+' '+(translation?'Välj vilket språk du vill svara på. ':'')+(lang==='sv-SE'||translation?'Ett svar visas efter fem sekunder.':'An answer appears after five seconds.'),icon:'Aa',color:'#c4afff',placeholder:lang==='sv-SE'||translation?'Skriv svaret…':'Type the answer…'};
}
// Preserve the established order, inserting each new group after its language.
const insert={swedishLong:specs.slice(0,2).map(s=>s[0]),englishLong:specs.slice(2).map(s=>s[0])},added=new Set(specs.map(s=>s[0])),ordered={};
for(const [id,mode] of Object.entries(SC.modes))if(!added.has(id)){ordered[id]=mode;for(const extra of insert[id]||[])ordered[extra]=SC.modes[extra];}
SC.modes=ordered;
})(globalThis);
