'use strict';
const fs=require('node:fs'),path=require('node:path');
const policy=fs.readFileSync(path.join(__dirname,'../resources/highscore-policy.js'),'utf8');
const worker=fs.readFileSync(path.join(__dirname,'worker-source.mjs'),'utf8');
fs.writeFileSync(path.join(__dirname,'worker.mjs'),'// Generated by node cloudflare/build.cjs. Deploy this entire file.\n'+policy+'\n'+worker);
console.log('Built cloudflare/worker.mjs');
