// Generated by node cloudflare/build.cjs. Deploy this entire file.
/* Shared by the browser and the generated Cloudflare Worker. Edit here, then
   run node cloudflare/build.cjs. This list is deliberately not shown in the UI. */
(function(root){
'use strict';
// Bump only the affected game's version when its scoring/rules change.
// Home stays on v1 during its initial tuning, by the owner's decision.
const versions=Object.freeze({city:'v2',food:'v2',garden:'v2',hive:'v2',paint:'v2',dinosaur:'v2',marshmallows:'v2',eggs:'v2',home:'v1'});
// Longer distinctive strings also match inside a name (including separated or
// simple leetspeak spellings). Short/ambiguous words only match complete tokens.
const substrings=`
fuck fucking fucker fuckers motherfuck motherfucker motherfucking clusterfuck
fuckface fuckhead fuckoff fuckyou fuckwit fucktard fuckboy fucknut
shithead shitface shitbag shitstain shitshow bullshit horseshit dipshit dumbshit
jackshit batshit asshat asshole arsehole asswipe assface dumbass jackass badarse
bitchface bitchass sonofabitch cockhead cocksucker cockface dickhead dickface
dickwad dickweed dickshit dickpic dickless pisshead pissface pissflap piss off
wanker wankstain wankface twatface twatwaffle douchebag douchecanoe scumbag
slutface whorehouse manwhore cumshot cumface cumdump cumslut cumstain
blowjob handjob rimjob deepthroat gangbang gangrape bukkake hentai
pornhub pornhub xxxporn hardcoreporn childporn kiddieporn sexvideo sextape
analrape buttplug buttsex analfist analfuck titfuck pussylick pussyeater
penis vagina clitoris testicle scrotum foreskin masturbation masturbate
orgasm ejaculation ejaculate erection dildo vibrator fellatio cunnilingus
pedophile paedophile pedophil paedophil necrophil zoophil bestiality
retarded retardation faggot fagotry nigga nigger chinkface whitepower
heilhitler siegheil hitler naziwhite killjews gasjews gas the jews
kill yourself kysyourself killallblacks rapevictim rapeyou schoolshooter
knulla knull knulled knullad knullare knullande knullat knullkompis
fitta fittor fittig fittans fittnylle fittunge fittskalle fittslick
kukhuvud kuksug kukhora kuken kukar kukjävel kukjavel kukfanskap
horunge horungar horjävel horjavel horhus horbock horfitta horaktig
skitstövel skitstovel skithög skithog skitunge skitjävel skitjavel skitfan
skitstövlar skitstovlar skitnödig skitnodig skitsnack skitansikte
rövknull rovknull rövhål rovhal rövslick rovslick rövskägg rovskagg
rövhuvud rovhuvud rövunge rovunge arsle arsel arselhål arselhal
helvete helvetes jävlar javlar jävla javla jävel javel jävlig javlig
jävul javul fanskap fanjävel fanjavel förbannad forbannad förbannat forbannat
runka runkar runkare runkig avsug avsugning ollon ollad ollning
sperma pungsvett pungkul pungpåse pungpase könsorgan konsorgan
knullfilm porrfilm porrhora porrstjärna porrstjarna barnporr
våldtäkt valdtakt våldta valdta våldtagen valdtagen våldtäktsman valdtaktsman
pedofil pedofili nekrofil zoofil tidelag knulla barn mörda morda
bögjävel bogjavel bögfan bogfan bögäckel bogackel bögunge bogunge
negerjävel negerjavel svartskalle blattejävel blattejavel blattehora
sieg heil heil hitler döda judar doda judar döda bögar doda bogar
ta livet av dig häng dig hang dig skjut dig döda dig doda dig
`.trim().split(/\n/).flatMap(line=>line.trim().split(/\s+/)).filter(Boolean);
// Phrases are separate entries so their individual words aren't overblocked.
const phrases=['piss off','gas the jews','kill yourself','knulla barn','sieg heil',
  'heil hitler','döda judar','döda bögar','ta livet av dig','häng dig','skjut dig','döda dig'];
const tokens=`ass arse shit piss crap bitch slut whore cock dick pussy cunt twat
fag homo retard nazi porn porno sex anal cum tits boob boobs titty titties
kuk röv rov bög bog hora horor fan satan skit bajs piss kiss porr sex
snopp snippa snoppis bröst brost blatte neger mongo cp`;
const normalize=value=>String(value).toLowerCase().normalize('NFKD')
  .replace(/\p{M}/gu,'').replace(/[013457@$!]/g,c=>({'0':'o','1':'i','3':'e','4':'a','5':'s','7':'t','@':'a','$':'s','!':'i'}[c]));
const compact=value=>normalize(value).replace(/[^a-z]/g,'');
// Exclude phrase components from the substring list: e.g. ordinary names can
// contain "dig", "barn", "off", "the" or "heil" without being abusive.
const phraseParts=new Set(phrases.flatMap(p=>normalize(p).split(/\s+/)));
const fragments=[...new Set([...substrings.filter(s=>!phraseParts.has(normalize(s))),...phrases].map(compact))].filter(s=>s.length>=4);
const words=new Set(tokens.split(/\s+/).map(normalize));
function isBannedName(value){
  const normalized=normalize(value),joined=compact(value);
  return fragments.some(fragment=>joined.includes(fragment)) ||
    normalized.split(/[^a-z]+/).some(token=>words.has(token)) || words.has(joined);
}
root.SkolarkadenHighscorePolicy=Object.freeze({versions,isBannedName});
})(globalThis);

// Paste this entire file into skolarkaden-api's Cloudflare editor and deploy.
// Required D1 binding: DB. Run schema.sql first. No browser API key is used.
const ALLOWED_ORIGIN = 'https://jakobrogstadius.github.io';
const GAMES = new Set(['city', 'food', 'garden', 'hive', 'paint', 'dinosaur', 'marshmallows', 'eggs', 'home']);
const LESSONS = new Set(['letters', 'swedish', 'swedishLong', 'english', 'englishLong',
  'bopomofo', 'chinese', 'chineseTrad2', 'chineseTrad3', 'chineseTrad4',
  'chineseSimpl1', 'chineseSimpl2', 'chineseSimpl3', 'chineseSimpl4',
  'math', 'math2', 'math3', 'math4', 'math5', 'math6']);
const PACES = new Set(['gentle', 'steady', 'brave']);
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

function validBoard(value) {
  if (typeof value !== 'string' || value.length > 160) return false;
  const [version, game, lesson, pace, extra] = value.split(':');
  return GAMES.has(game) && version === globalThis.SkolarkadenHighscorePolicy.versions[game] &&
    LESSONS.has(lesson) && PACES.has(pace) && extra === undefined;
}

async function readBody(request) {
  // Enforce the actual streamed size, including requests without Content-Length.
  const reader = request.body?.getReader();
  if (!reader) throw new Error('invalid_json');
  const chunks = []; let size = 0;
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      size += value.byteLength;
      if (size > 2048) { await reader.cancel(); throw new Error('body_too_large'); }
      chunks.push(value);
    }
  } finally { reader.releaseLock(); }
  const bytes = new Uint8Array(size); let offset = 0;
  for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; }
  try { return JSON.parse(new TextDecoder().decode(bytes)); }
  catch (_) { throw new Error('invalid_json'); }
}

async function allowSubmission(request, db) {
  const ip = request.headers.get('CF-Connecting-IP');
  if (!ip) throw new Error('Missing Cloudflare client address');
  const now = Math.floor(Date.now() / 1000), window = Math.floor(now / 60) * 60;
  // Rate counters use daily IP hashes, independently of IPs retained in score
  // rows. Clean expired counters on submissions; these are not player identities.
  const bytes = new TextEncoder().encode('skolarkaden:' + Math.floor(now / 86400) + ':' + ip);
  const hash = await crypto.subtle.digest('SHA-256', bytes);
  const key = Array.from(new Uint8Array(hash), b => b.toString(16).padStart(2, '0')).join('');
  await db.prepare('DELETE FROM score_rate_limits WHERE expires_at < ?').bind(now).run();
  const row = await db.prepare(`
    INSERT INTO score_rate_limits (client_key, window_start, attempts, expires_at)
    VALUES (?, ?, 1, ?)
    ON CONFLICT(client_key) DO UPDATE SET
      attempts = CASE WHEN window_start = excluded.window_start THEN attempts + 1 ELSE 1 END,
      window_start = excluded.window_start, expires_at = excluded.expires_at
    RETURNING attempts
  `).bind(key, window, now + 3600).first();
  // Shared school connections can have many simultaneous players.
  return row.attempts <= 120;
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url), origin = request.headers.get('Origin');
    const headers = { 'Cache-Control': 'no-store', 'Vary': 'Origin' };
    if (origin === ALLOWED_ORIGIN) {
      headers['Access-Control-Allow-Origin'] = origin;
      headers['Access-Control-Allow-Methods'] = 'GET, POST, OPTIONS';
      headers['Access-Control-Allow-Headers'] = 'Content-Type';
    }
    const reply = (body, status = 200, extra = {}) => Response.json(body, { status, headers: { ...headers, ...extra } });
    if (origin && origin !== ALLOWED_ORIGIN) return reply({ error: 'origin_not_allowed' }, 403);
    if (request.method === 'OPTIONS' && url.pathname === '/scores') {
      return new Response(null, { status: 204, headers });
    }
    try {
      if (request.method === 'GET' && url.pathname === '/health') {
        await env.DB.prepare('SELECT submission_id, ip FROM highscores LIMIT 1').all();
        await env.DB.prepare('SELECT client_key FROM score_rate_limits LIMIT 1').all();
        return reply({ ok: true, database: 'connected', api: 'highscores-v1' });
      }
      if (url.pathname !== '/scores') return reply({ error: 'not_found' }, 404);
      if (request.method === 'GET') {
        const board = url.searchParams.get('leaderboard');
        if (!validBoard(board)) return reply({ error: 'invalid_leaderboard' }, 400);
        const submission = url.searchParams.get('submission') || '';
        const rawScore = url.searchParams.get('score');
        if ((submission && !UUID.test(submission)) || (rawScore !== null &&
            (!/^\d+$/.test(rawScore) || Number(rawScore) > 1000000))) return reply({ error: 'invalid_score' }, 400);
        const { results } = await env.DB.prepare(`
          SELECT player_name, score, created_at, submission_id = ? AS is_player FROM highscores
          WHERE leaderboard_key = ? ORDER BY score DESC, created_at ASC, submission_id ASC LIMIT 10
        `).bind(submission, board).all();
        const own = submission ? await env.DB.prepare(`SELECT score, created_at, submission_id FROM highscores
          WHERE leaderboard_key = ? AND submission_id = ?`).bind(board, submission).first() : null;
        let rank = null;
        if (own) {
          const row = await env.DB.prepare(`SELECT count(*) AS n FROM highscores WHERE leaderboard_key = ? AND
            (score > ? OR (score = ? AND (created_at < ? OR (created_at = ? AND submission_id <= ?))))`)
            .bind(board, own.score, own.score, own.created_at, own.created_at, own.submission_id).first();
          rank = row.n;
        } else if (rawScore !== null) {
          const row = await env.DB.prepare('SELECT count(*) AS n FROM highscores WHERE leaderboard_key = ? AND score >= ?')
            .bind(board, Number(rawScore)).first();
          rank = row.n + 1;
        }
        return reply({ leaderboard: board, scores: results, rank, saved: Boolean(own) });
      }
      if (request.method !== 'POST') return reply({ error: 'method_not_allowed' }, 405, { Allow: 'GET, POST, OPTIONS' });
      if (origin !== ALLOWED_ORIGIN) return reply({ error: 'origin_required' }, 403);
      if (request.headers.get('Content-Type')?.split(';')[0].trim().toLowerCase() !== 'application/json') {
        return reply({ error: 'json_required' }, 415);
      }
      const body = await readBody(request);
      if (!body || typeof body !== 'object' || Array.isArray(body)) return reply({ error: 'invalid_score' }, 400);
      const { submission_id: id, leaderboard_key: board, score } = body;
      const name = typeof body.player_name === 'string' ? body.player_name.normalize('NFC').trim().toUpperCase() || 'ANONYM' : 'ANONYM';
      // Mirror the browser's silent drop; direct API calls cannot bypass it.
      if (globalThis.SkolarkadenHighscorePolicy.isBannedName(name)) return reply({ ok: true });
      if (typeof id !== 'string' || !UUID.test(id) || !validBoard(board) ||
          !/^[\p{L}\p{M} ]{1,10}$/u.test(name) ||
          !Number.isSafeInteger(score) || score < 0 || score > 1000000) {
        return reply({ error: 'invalid_score' }, 400);
      }
      if (!await allowSubmission(request, env.DB)) return reply({ error: 'rate_limited' }, 429, { 'Retry-After': '60' });
      const result = await env.DB.prepare(`
        INSERT INTO highscores (submission_id, leaderboard_key, player_name, score, ip)
        VALUES (?, ?, ?, ?, ?) ON CONFLICT(submission_id) DO NOTHING
      `).bind(id, board, name, score, request.headers.get('CF-Connecting-IP')).run();
      if (!result.meta.changes) {
        const existing = await env.DB.prepare(`
          SELECT leaderboard_key, player_name, score FROM highscores WHERE submission_id = ?
        `).bind(id).first();
        if (existing.leaderboard_key !== board || existing.player_name !== name || existing.score !== score) {
          return reply({ error: 'submission_conflict' }, 409);
        }
      }
      return reply({ ok: true }, result.meta.changes ? 201 : 200);
    } catch (error) {
      if (error.message === 'body_too_large') return reply({ error: error.message }, 413);
      if (error.message === 'invalid_json') return reply({ error: error.message }, 400);
      console.error(error);
      return reply({ ok: false, error: 'service_unavailable' }, 503);
    }
  }
};
